# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'buscarpaciente.ui'
#
# Created: Thu Feb  5 18:18:57 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MostrarPaciente(object):
    def setupUi(self, MostrarPaciente):
        MostrarPaciente.setObjectName(_fromUtf8("MostrarPaciente"))
        MostrarPaciente.resize(486, 522)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("./img/aav50.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MostrarPaciente.setWindowIcon(icon)
        self.centralWidget = QtGui.QWidget(MostrarPaciente)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.tab = QtGui.QTabWidget(self.centralWidget)
        self.tab.setGeometry(QtCore.QRect(0, 0, 481, 451))
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tabDatos = QtGui.QWidget()
        self.tabDatos.setObjectName(_fromUtf8("tabDatos"))
        self.widget = QtGui.QWidget(self.tabDatos)
        self.widget.setGeometry(QtCore.QRect(10, 10, 461, 407))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 10, 2, 1, 1)
        self.line_3 = QtGui.QFrame(self.widget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 15, 0, 1, 4)
        self.label = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 7, 2, 1, 1)
        self.lEmail = QtGui.QLabel(self.widget)
        self.lEmail.setObjectName(_fromUtf8("lEmail"))
        self.gridLayout.addWidget(self.lEmail, 8, 2, 1, 2)
        self.line_2 = QtGui.QFrame(self.widget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 12, 0, 1, 4)
        self.lActividades = QtGui.QTextEdit(self.widget)
        self.lActividades.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lActividades.setObjectName(_fromUtf8("lActividades"))
        self.gridLayout.addWidget(self.lActividades, 14, 0, 1, 4)
        self.lHActividad = QtGui.QLabel(self.widget)
        self.lHActividad.setObjectName(_fromUtf8("lHActividad"))
        self.gridLayout.addWidget(self.lHActividad, 13, 3, 1, 1)
        self.lNombre = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lNombre.setFont(font)
        self.lNombre.setObjectName(_fromUtf8("lNombre"))
        self.gridLayout.addWidget(self.lNombre, 5, 0, 1, 2)
        self.lApellido = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lApellido.setFont(font)
        self.lApellido.setObjectName(_fromUtf8("lApellido"))
        self.gridLayout.addWidget(self.lApellido, 5, 2, 1, 2)
        self.label_4 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 13, 0, 1, 2)
        self.label_5 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 10, 0, 1, 2)
        self.lHOcupacion = QtGui.QLabel(self.widget)
        self.lHOcupacion.setObjectName(_fromUtf8("lHOcupacion"))
        self.gridLayout.addWidget(self.lHOcupacion, 10, 3, 1, 1)
        self.lFecha = QtGui.QLabel(self.widget)
        self.lFecha.setObjectName(_fromUtf8("lFecha"))
        self.gridLayout.addWidget(self.lFecha, 7, 1, 1, 1)
        self.label1 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setObjectName(_fromUtf8("label1"))
        self.gridLayout.addWidget(self.label1, 7, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 8, 0, 1, 2)
        self.label_7 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 16, 0, 1, 1)
        self.line = QtGui.QFrame(self.widget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 9, 0, 1, 4)
        self.lOcupacion = QtGui.QLabel(self.widget)
        self.lOcupacion.setObjectName(_fromUtf8("lOcupacion"))
        self.gridLayout.addWidget(self.lOcupacion, 11, 0, 1, 4)
        self.lFono = QtGui.QLabel(self.widget)
        self.lFono.setObjectName(_fromUtf8("lFono"))
        self.gridLayout.addWidget(self.lFono, 7, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 13, 2, 1, 1)
        self.botonEditar = QtGui.QPushButton(self.widget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("./img/edit24.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonEditar.setIcon(icon1)
        self.botonEditar.setObjectName(_fromUtf8("botonEditar"))
        self.gridLayout.addWidget(self.botonEditar, 1, 3, 1, 1)
        self.lRun = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lRun.setFont(font)
        self.lRun.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lRun.setAlignment(QtCore.Qt.AlignCenter)
        self.lRun.setObjectName(_fromUtf8("lRun"))
        self.gridLayout.addWidget(self.lRun, 1, 0, 1, 3)
        self.lMotivo = QtGui.QTextEdit(self.widget)
        self.lMotivo.setObjectName(_fromUtf8("lMotivo"))
        self.gridLayout.addWidget(self.lMotivo, 16, 1, 1, 3)
        self.line_4 = QtGui.QFrame(self.widget)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout.addWidget(self.line_4, 6, 0, 1, 4)
        self.tab.addTab(self.tabDatos, _fromUtf8(""))
        self.tabSintomas = QtGui.QWidget()
        self.tabSintomas.setObjectName(_fromUtf8("tabSintomas"))
        self.nuevoSintoma = QtGui.QPushButton(self.tabSintomas)
        self.nuevoSintoma.setGeometry(QtCore.QRect(10, 360, 171, 51))
        self.nuevoSintoma.setIcon(icon1)
        self.nuevoSintoma.setObjectName(_fromUtf8("nuevoSintoma"))
        self.verSintoma = QtGui.QPushButton(self.tabSintomas)
        self.verSintoma.setGeometry(QtCore.QRect(340, 10, 99, 27))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("./img/view16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.verSintoma.setIcon(icon2)
        self.verSintoma.setObjectName(_fromUtf8("verSintoma"))
        self.elimSintoma = QtGui.QPushButton(self.tabSintomas)
        self.elimSintoma.setGeometry(QtCore.QRect(340, 100, 99, 27))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("./img/delete16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.elimSintoma.setIcon(icon3)
        self.elimSintoma.setObjectName(_fromUtf8("elimSintoma"))
        self.treeSintomas = QtGui.QTreeWidget(self.tabSintomas)
        self.treeSintomas.setGeometry(QtCore.QRect(10, 10, 321, 341))
        self.treeSintomas.setObjectName(_fromUtf8("treeSintomas"))
        self.tab.addTab(self.tabSintomas, _fromUtf8(""))
        self.tabEvaluacion = QtGui.QWidget()
        self.tabEvaluacion.setObjectName(_fromUtf8("tabEvaluacion"))
        self.nuevaEval = QtGui.QPushButton(self.tabEvaluacion)
        self.nuevaEval.setGeometry(QtCore.QRect(10, 360, 131, 51))
        self.nuevaEval.setIcon(icon1)
        self.nuevaEval.setObjectName(_fromUtf8("nuevaEval"))
        self.treeEval = QtGui.QTreeWidget(self.tabEvaluacion)
        self.treeEval.setGeometry(QtCore.QRect(10, 10, 321, 341))
        self.treeEval.setObjectName(_fromUtf8("treeEval"))
        self.verEval = QtGui.QPushButton(self.tabEvaluacion)
        self.verEval.setGeometry(QtCore.QRect(340, 10, 99, 27))
        self.verEval.setIcon(icon2)
        self.verEval.setObjectName(_fromUtf8("verEval"))
        self.elimEval = QtGui.QPushButton(self.tabEvaluacion)
        self.elimEval.setGeometry(QtCore.QRect(340, 100, 99, 27))
        self.elimEval.setIcon(icon3)
        self.elimEval.setObjectName(_fromUtf8("elimEval"))
        self.tab.addTab(self.tabEvaluacion, _fromUtf8(""))
        MostrarPaciente.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MostrarPaciente)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 486, 25))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        MostrarPaciente.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MostrarPaciente)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MostrarPaciente.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MostrarPaciente)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MostrarPaciente.setStatusBar(self.statusBar)

        self.retranslateUi(MostrarPaciente)
        self.tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MostrarPaciente)

    def retranslateUi(self, MostrarPaciente):
        MostrarPaciente.setWindowTitle(_translate("MostrarPaciente", "BuscarPaciente", None))
        self.label_2.setText(_translate("MostrarPaciente", "Horas uso:", None))
        self.label.setText(_translate("MostrarPaciente", "Teléfono:", None))
        self.lEmail.setText(_translate("MostrarPaciente", "lEmail", None))
        self.lHActividad.setText(_translate("MostrarPaciente", "lHActividad", None))
        self.lNombre.setText(_translate("MostrarPaciente", "lNombre", None))
        self.lApellido.setText(_translate("MostrarPaciente", "lApellido", None))
        self.label_4.setText(_translate("MostrarPaciente", "Actividades extra que requieren\n"
"uso vocal constante o aumentado:", None))
        self.label_5.setText(_translate("MostrarPaciente", "Ocupación:", None))
        self.lHOcupacion.setText(_translate("MostrarPaciente", "lHOcupacion", None))
        self.lFecha.setText(_translate("MostrarPaciente", "lFecha", None))
        self.label1.setText(_translate("MostrarPaciente", "Fecha nacimiento:", None))
        self.label_3.setText(_translate("MostrarPaciente", "Correo electrónico:", None))
        self.label_7.setText(_translate("MostrarPaciente", "Motivo Consulta:", None))
        self.lOcupacion.setText(_translate("MostrarPaciente", "lOcupacion", None))
        self.lFono.setText(_translate("MostrarPaciente", "lFono", None))
        self.label_6.setText(_translate("MostrarPaciente", "Horas uso:", None))
        self.botonEditar.setText(_translate("MostrarPaciente", "Editar\n"
"datos", None))
        self.lRun.setText(_translate("MostrarPaciente", "lRun", None))
        self.tab.setTabText(self.tab.indexOf(self.tabDatos), _translate("MostrarPaciente", "Datos Personales", None))
        self.nuevoSintoma.setText(_translate("MostrarPaciente", "Nueva\n"
"Sintomatología", None))
        self.verSintoma.setText(_translate("MostrarPaciente", "Ver", None))
        self.elimSintoma.setText(_translate("MostrarPaciente", "Eliminar", None))
        self.treeSintomas.headerItem().setText(0, _translate("MostrarPaciente", "Id", None))
        self.treeSintomas.headerItem().setText(1, _translate("MostrarPaciente", "Fecha", None))
        self.tab.setTabText(self.tab.indexOf(self.tabSintomas), _translate("MostrarPaciente", "Sintomatología y Conductas", None))
        self.nuevaEval.setText(_translate("MostrarPaciente", "Nueva\n"
"Evaluación", None))
        self.treeEval.headerItem().setText(0, _translate("MostrarPaciente", "Id", None))
        self.treeEval.headerItem().setText(1, _translate("MostrarPaciente", "Fecha", None))
        self.verEval.setText(_translate("MostrarPaciente", "Ver", None))
        self.elimEval.setText(_translate("MostrarPaciente", "Eliminar", None))
        self.tab.setTabText(self.tab.indexOf(self.tabEvaluacion), _translate("MostrarPaciente", "Evaluación Vocal", None))

