# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'consultaevocal.ui'
#
# Created: Tue Feb 10 13:52:39 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_vistaEvocal(object):
    def setupUi(self, vistaEvocal):
        vistaEvocal.setObjectName(_fromUtf8("vistaEvocal"))
        vistaEvocal.resize(690, 587)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../sw/voz/dungun/anamnesis-gui/img/aav.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        vistaEvocal.setWindowIcon(icon)
        self.centralWidget = QtGui.QWidget(vistaEvocal)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.toolBox = QtGui.QToolBox(self.centralWidget)
        self.toolBox.setGeometry(QtCore.QRect(10, 30, 671, 491))
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.tab1 = QtGui.QWidget()
        self.tab1.setGeometry(QtCore.QRect(0, 0, 671, 367))
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.layoutWidget = QtGui.QWidget(self.tab1)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 11, 651, 61))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 1, 2, 1)
        self.labelFIsica = QtGui.QLabel(self.layoutWidget)
        self.labelFIsica.setObjectName(_fromUtf8("labelFIsica"))
        self.gridLayout.addWidget(self.labelFIsica, 0, 2, 2, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 3, 2, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 4, 1, 1)
        self.lcdVHITotal = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdVHITotal.setObjectName(_fromUtf8("lcdVHITotal"))
        self.gridLayout.addWidget(self.lcdVHITotal, 1, 4, 2, 1)
        self.label = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 3, 1)
        self.lcdVHIFun = QtGui.QLCDNumber(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lcdVHIFun.setFont(font)
        self.lcdVHIFun.setObjectName(_fromUtf8("lcdVHIFun"))
        self.gridLayout.addWidget(self.lcdVHIFun, 2, 1, 1, 1)
        self.lcdVHIFis = QtGui.QLCDNumber(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lcdVHIFis.setFont(font)
        self.lcdVHIFis.setObjectName(_fromUtf8("lcdVHIFis"))
        self.gridLayout.addWidget(self.lcdVHIFis, 2, 2, 1, 1)
        self.lcdVHIEmo = QtGui.QLCDNumber(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lcdVHIEmo.setFont(font)
        self.lcdVHIEmo.setObjectName(_fromUtf8("lcdVHIEmo"))
        self.gridLayout.addWidget(self.lcdVHIEmo, 2, 3, 1, 1)
        self.layoutWidget1 = QtGui.QWidget(self.tab1)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 90, 652, 244))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.line_7 = QtGui.QFrame(self.layoutWidget1)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.gridLayout_2.addWidget(self.line_7, 3, 0, 1, 3)
        self.line_4 = QtGui.QFrame(self.layoutWidget1)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_2.addWidget(self.line_4, 1, 0, 1, 3)
        self.label_7 = QtGui.QLabel(self.layoutWidget1)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 2)
        self.label_10 = QtGui.QLabel(self.layoutWidget1)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 4, 4, 1, 2)
        self.label_5 = QtGui.QLabel(self.layoutWidget1)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 2)
        self.label_9 = QtGui.QLabel(self.layoutWidget1)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 4, 0, 1, 2)
        self.line_10 = QtGui.QFrame(self.layoutWidget1)
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.gridLayout_2.addWidget(self.line_10, 5, 4, 1, 3)
        self.lcdtmf = QtGui.QLCDNumber(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lcdtmf.setFont(font)
        self.lcdtmf.setObjectName(_fromUtf8("lcdtmf"))
        self.gridLayout_2.addWidget(self.lcdtmf, 6, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.layoutWidget1)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 6, 0, 1, 2)
        self.label_13 = QtGui.QLabel(self.layoutWidget1)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 6, 4, 1, 2)
        self.label_6 = QtGui.QLabel(self.layoutWidget1)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 4, 1, 2)
        self.label_8 = QtGui.QLabel(self.layoutWidget1)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 2, 4, 1, 2)
        self.line_6 = QtGui.QFrame(self.layoutWidget1)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.gridLayout_2.addWidget(self.line_6, 1, 4, 1, 3)
        self.line_8 = QtGui.QFrame(self.layoutWidget1)
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.gridLayout_2.addWidget(self.line_8, 3, 4, 1, 3)
        self.labelmrr = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelmrr.setFont(font)
        self.labelmrr.setObjectName(_fromUtf8("labelmrr"))
        self.gridLayout_2.addWidget(self.labelmrr, 2, 2, 1, 1)
        self.line_9 = QtGui.QFrame(self.layoutWidget1)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.gridLayout_2.addWidget(self.line_9, 5, 0, 1, 3)
        self.label_53 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_53.setFont(font)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.gridLayout_2.addWidget(self.label_53, 0, 6, 1, 1)
        self.labeltrr = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labeltrr.setFont(font)
        self.labeltrr.setObjectName(_fromUtf8("labeltrr"))
        self.gridLayout_2.addWidget(self.labeltrr, 0, 2, 1, 1)
        self.line_12 = QtGui.QFrame(self.layoutWidget1)
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.gridLayout_2.addWidget(self.line_12, 7, 4, 1, 3)
        self.label_12 = QtGui.QLabel(self.layoutWidget1)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 8, 0, 1, 2)
        self.line_3 = QtGui.QFrame(self.layoutWidget1)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_2.addWidget(self.line_3, 0, 3, 9, 1)
        self.lcdnidc = QtGui.QLCDNumber(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lcdnidc.setFont(font)
        self.lcdnidc.setObjectName(_fromUtf8("lcdnidc"))
        self.gridLayout_2.addWidget(self.lcdnidc, 4, 6, 1, 1)
        self.labelmrf = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelmrf.setFont(font)
        self.labelmrf.setObjectName(_fromUtf8("labelmrf"))
        self.gridLayout_2.addWidget(self.labelmrf, 2, 6, 1, 1)
        self.lcdtme = QtGui.QLCDNumber(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lcdtme.setFont(font)
        self.lcdtme.setObjectName(_fromUtf8("lcdtme"))
        self.gridLayout_2.addWidget(self.lcdtme, 6, 6, 1, 1)
        self.line_11 = QtGui.QFrame(self.layoutWidget1)
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.gridLayout_2.addWidget(self.line_11, 7, 0, 1, 3)
        self.labelcrf = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelcrf.setFont(font)
        self.labelcrf.setObjectName(_fromUtf8("labelcrf"))
        self.gridLayout_2.addWidget(self.labelcrf, 4, 2, 1, 1)
        self.lcdisa = QtGui.QLCDNumber(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lcdisa.setFont(font)
        self.lcdisa.setObjectName(_fromUtf8("lcdisa"))
        self.gridLayout_2.addWidget(self.lcdisa, 8, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.layoutWidget1)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 8, 4, 1, 2)
        self.labelar = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelar.setFont(font)
        self.labelar.setObjectName(_fromUtf8("labelar"))
        self.gridLayout_2.addWidget(self.labelar, 8, 6, 1, 1)
        self.toolBox.addItem(self.tab1, _fromUtf8(""))
        self.tab2 = QtGui.QWidget()
        self.tab2.setGeometry(QtCore.QRect(0, 0, 671, 367))
        self.tab2.setObjectName(_fromUtf8("tab2"))
        self.layoutWidget2 = QtGui.QWidget(self.tab2)
        self.layoutWidget2.setGeometry(QtCore.QRect(30, 210, 586, 134))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_23 = QtGui.QLabel(self.layoutWidget2)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_4.addWidget(self.label_23, 0, 5, 1, 1)
        self.label_21 = QtGui.QLabel(self.layoutWidget2)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_4.addWidget(self.label_21, 0, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.layoutWidget2)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_4.addWidget(self.label_22, 0, 3, 1, 1)
        self.label_20 = QtGui.QLabel(self.layoutWidget2)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_4.addWidget(self.label_20, 3, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.layoutWidget2)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_4.addWidget(self.label_25, 3, 3, 1, 1)
        self.label_26 = QtGui.QLabel(self.layoutWidget2)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_4.addWidget(self.label_26, 3, 5, 1, 1)
        self.labeltal = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labeltal.setFont(font)
        self.labeltal.setObjectName(_fromUtf8("labeltal"))
        self.gridLayout_4.addWidget(self.labeltal, 4, 5, 1, 1)
        self.labeltg = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labeltg.setFont(font)
        self.labeltg.setObjectName(_fromUtf8("labeltg"))
        self.gridLayout_4.addWidget(self.labeltg, 1, 1, 1, 1)
        self.line_36 = QtGui.QFrame(self.layoutWidget2)
        self.line_36.setFrameShape(QtGui.QFrame.VLine)
        self.line_36.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_36.setObjectName(_fromUtf8("line_36"))
        self.gridLayout_4.addWidget(self.line_36, 0, 2, 2, 1)
        self.label_24 = QtGui.QLabel(self.layoutWidget2)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_4.addWidget(self.label_24, 0, 0, 5, 1)
        self.labelti = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelti.setFont(font)
        self.labelti.setObjectName(_fromUtf8("labelti"))
        self.gridLayout_4.addWidget(self.labelti, 1, 3, 1, 1)
        self.line_35 = QtGui.QFrame(self.layoutWidget2)
        self.line_35.setFrameShape(QtGui.QFrame.HLine)
        self.line_35.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_35.setObjectName(_fromUtf8("line_35"))
        self.gridLayout_4.addWidget(self.line_35, 2, 1, 1, 5)
        self.labelts = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelts.setFont(font)
        self.labelts.setObjectName(_fromUtf8("labelts"))
        self.gridLayout_4.addWidget(self.labelts, 1, 5, 1, 1)
        self.labeltce = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labeltce.setFont(font)
        self.labeltce.setObjectName(_fromUtf8("labeltce"))
        self.gridLayout_4.addWidget(self.labeltce, 4, 3, 1, 1)
        self.labeltc = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labeltc.setFont(font)
        self.labeltc.setObjectName(_fromUtf8("labeltc"))
        self.gridLayout_4.addWidget(self.labeltc, 4, 1, 1, 1)
        self.line_37 = QtGui.QFrame(self.layoutWidget2)
        self.line_37.setFrameShape(QtGui.QFrame.VLine)
        self.line_37.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_37.setObjectName(_fromUtf8("line_37"))
        self.gridLayout_4.addWidget(self.line_37, 0, 4, 2, 1)
        self.line_38 = QtGui.QFrame(self.layoutWidget2)
        self.line_38.setFrameShape(QtGui.QFrame.VLine)
        self.line_38.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_38.setObjectName(_fromUtf8("line_38"))
        self.gridLayout_4.addWidget(self.line_38, 3, 2, 2, 1)
        self.line_39 = QtGui.QFrame(self.layoutWidget2)
        self.line_39.setFrameShape(QtGui.QFrame.VLine)
        self.line_39.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_39.setObjectName(_fromUtf8("line_39"))
        self.gridLayout_4.addWidget(self.line_39, 3, 4, 2, 1)
        self.label_27 = QtGui.QLabel(self.tab2)
        self.label_27.setGeometry(QtCore.QRect(500, 0, 111, 20))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.obspt = QtGui.QTextEdit(self.tab2)
        self.obspt.setGeometry(QtCore.QRect(480, 20, 191, 181))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.obspt.setFont(font)
        self.obspt.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.obspt.setObjectName(_fromUtf8("obspt"))
        self.layoutWidget3 = QtGui.QWidget(self.tab2)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 10, 478, 151))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.labelppp3 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelppp3.setFont(font)
        self.labelppp3.setObjectName(_fromUtf8("labelppp3"))
        self.gridLayout_3.addWidget(self.labelppp3, 4, 5, 1, 1)
        self.label_16 = QtGui.QLabel(self.layoutWidget3)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 1, 3, 1, 1)
        self.label_17 = QtGui.QLabel(self.layoutWidget3)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_3.addWidget(self.label_17, 1, 5, 1, 1)
        self.line_33 = QtGui.QFrame(self.layoutWidget3)
        self.line_33.setFrameShape(QtGui.QFrame.VLine)
        self.line_33.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_33.setObjectName(_fromUtf8("line_33"))
        self.gridLayout_3.addWidget(self.line_33, 1, 2, 4, 1)
        self.labelppl2 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelppl2.setFont(font)
        self.labelppl2.setObjectName(_fromUtf8("labelppl2"))
        self.gridLayout_3.addWidget(self.labelppl2, 3, 3, 1, 1)
        self.label_19 = QtGui.QLabel(self.layoutWidget3)
        self.label_19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_3.addWidget(self.label_19, 0, 0, 1, 6)
        self.label_18 = QtGui.QLabel(self.layoutWidget3)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_3.addWidget(self.label_18, 1, 0, 4, 1)
        self.labelppf3 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelppf3.setFont(font)
        self.labelppf3.setObjectName(_fromUtf8("labelppf3"))
        self.gridLayout_3.addWidget(self.labelppf3, 4, 1, 1, 1)
        self.labelppp1 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelppp1.setFont(font)
        self.labelppp1.setObjectName(_fromUtf8("labelppp1"))
        self.gridLayout_3.addWidget(self.labelppp1, 2, 5, 1, 1)
        self.label_15 = QtGui.QLabel(self.layoutWidget3)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_3.addWidget(self.label_15, 1, 1, 1, 1)
        self.labelppp2 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelppp2.setFont(font)
        self.labelppp2.setObjectName(_fromUtf8("labelppp2"))
        self.gridLayout_3.addWidget(self.labelppp2, 3, 5, 1, 1)
        self.labelppf2 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelppf2.setFont(font)
        self.labelppf2.setObjectName(_fromUtf8("labelppf2"))
        self.gridLayout_3.addWidget(self.labelppf2, 3, 1, 1, 1)
        self.labelppl1 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelppl1.setFont(font)
        self.labelppl1.setObjectName(_fromUtf8("labelppl1"))
        self.gridLayout_3.addWidget(self.labelppl1, 2, 3, 1, 1)
        self.labelppl3 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelppl3.setFont(font)
        self.labelppl3.setObjectName(_fromUtf8("labelppl3"))
        self.gridLayout_3.addWidget(self.labelppl3, 4, 3, 1, 1)
        self.labelppf1 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelppf1.setFont(font)
        self.labelppf1.setObjectName(_fromUtf8("labelppf1"))
        self.gridLayout_3.addWidget(self.labelppf1, 2, 1, 1, 1)
        self.line_34 = QtGui.QFrame(self.layoutWidget3)
        self.line_34.setFrameShape(QtGui.QFrame.VLine)
        self.line_34.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_34.setObjectName(_fromUtf8("line_34"))
        self.gridLayout_3.addWidget(self.line_34, 1, 4, 4, 1)
        self.toolBox.addItem(self.tab2, _fromUtf8(""))
        self.tab3 = QtGui.QWidget()
        self.tab3.setGeometry(QtCore.QRect(0, 0, 671, 367))
        self.tab3.setObjectName(_fromUtf8("tab3"))
        self.layoutWidget_2 = QtGui.QWidget(self.tab3)
        self.layoutWidget_2.setGeometry(QtCore.QRect(50, 0, 501, 151))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget_2)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.line_14 = QtGui.QFrame(self.layoutWidget_2)
        self.line_14.setFrameShape(QtGui.QFrame.HLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName(_fromUtf8("line_14"))
        self.gridLayout_5.addWidget(self.line_14, 2, 1, 1, 1)
        self.label_28 = QtGui.QLabel(self.layoutWidget_2)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_5.addWidget(self.label_28, 0, 5, 1, 1)
        self.line_2 = QtGui.QFrame(self.layoutWidget_2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_5.addWidget(self.line_2, 2, 3, 1, 1)
        self.line_13 = QtGui.QFrame(self.layoutWidget_2)
        self.line_13.setFrameShape(QtGui.QFrame.VLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.gridLayout_5.addWidget(self.line_13, 0, 4, 5, 1)
        self.label_31 = QtGui.QLabel(self.layoutWidget_2)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_5.addWidget(self.label_31, 0, 3, 1, 1)
        self.label_30 = QtGui.QLabel(self.layoutWidget_2)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_5.addWidget(self.label_30, 0, 1, 1, 1)
        self.label_32 = QtGui.QLabel(self.layoutWidget_2)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_5.addWidget(self.label_32, 3, 1, 1, 1)
        self.label_33 = QtGui.QLabel(self.layoutWidget_2)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_5.addWidget(self.label_33, 3, 3, 1, 1)
        self.label_34 = QtGui.QLabel(self.layoutWidget_2)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_5.addWidget(self.label_34, 3, 5, 1, 1)
        self.lcdhpt = QtGui.QLCDNumber(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lcdhpt.setFont(font)
        self.lcdhpt.setObjectName(_fromUtf8("lcdhpt"))
        self.gridLayout_5.addWidget(self.lcdhpt, 4, 5, 1, 1)
        self.lcdhde = QtGui.QLCDNumber(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lcdhde.setFont(font)
        self.lcdhde.setObjectName(_fromUtf8("lcdhde"))
        self.gridLayout_5.addWidget(self.lcdhde, 4, 1, 1, 1)
        self.lcdhec = QtGui.QLCDNumber(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lcdhec.setFont(font)
        self.lcdhec.setObjectName(_fromUtf8("lcdhec"))
        self.gridLayout_5.addWidget(self.lcdhec, 1, 3, 1, 1)
        self.lcdhpa = QtGui.QLCDNumber(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lcdhpa.setFont(font)
        self.lcdhpa.setObjectName(_fromUtf8("lcdhpa"))
        self.gridLayout_5.addWidget(self.lcdhpa, 1, 1, 1, 1)
        self.line = QtGui.QFrame(self.layoutWidget_2)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_5.addWidget(self.line, 0, 2, 5, 1)
        self.lcdhpp = QtGui.QLCDNumber(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lcdhpp.setFont(font)
        self.lcdhpp.setObjectName(_fromUtf8("lcdhpp"))
        self.gridLayout_5.addWidget(self.lcdhpp, 1, 5, 1, 1)
        self.label_29 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_5.addWidget(self.label_29, 0, 0, 5, 1)
        self.lcdhrh = QtGui.QLCDNumber(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lcdhrh.setFont(font)
        self.lcdhrh.setObjectName(_fromUtf8("lcdhrh"))
        self.gridLayout_5.addWidget(self.lcdhrh, 4, 3, 1, 1)
        self.line_15 = QtGui.QFrame(self.layoutWidget_2)
        self.line_15.setFrameShape(QtGui.QFrame.HLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName(_fromUtf8("line_15"))
        self.gridLayout_5.addWidget(self.line_15, 2, 5, 1, 1)
        self.layoutWidget_3 = QtGui.QWidget(self.tab3)
        self.layoutWidget_3.setGeometry(QtCore.QRect(40, 160, 531, 131))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.gridLayout_6 = QtGui.QGridLayout(self.layoutWidget_3)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.line_17 = QtGui.QFrame(self.layoutWidget_3)
        self.line_17.setFrameShape(QtGui.QFrame.VLine)
        self.line_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_17.setObjectName(_fromUtf8("line_17"))
        self.gridLayout_6.addWidget(self.line_17, 3, 4, 5, 1)
        self.label_40 = QtGui.QLabel(self.layoutWidget_3)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_6.addWidget(self.label_40, 6, 3, 1, 1)
        self.label_41 = QtGui.QLabel(self.layoutWidget_3)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_6.addWidget(self.label_41, 6, 5, 1, 1)
        self.label_38 = QtGui.QLabel(self.layoutWidget_3)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_6.addWidget(self.label_38, 3, 3, 1, 1)
        self.label_39 = QtGui.QLabel(self.layoutWidget_3)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_6.addWidget(self.label_39, 6, 1, 1, 1)
        self.label_37 = QtGui.QLabel(self.layoutWidget_3)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_6.addWidget(self.label_37, 3, 1, 1, 1)
        self.label_35 = QtGui.QLabel(self.layoutWidget_3)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_6.addWidget(self.label_35, 3, 5, 1, 1)
        self.labelri = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelri.setFont(font)
        self.labelri.setObjectName(_fromUtf8("labelri"))
        self.gridLayout_6.addWidget(self.labelri, 7, 5, 1, 1)
        self.labelra = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelra.setFont(font)
        self.labelra.setObjectName(_fromUtf8("labelra"))
        self.gridLayout_6.addWidget(self.labelra, 4, 3, 1, 1)
        self.labelras = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelras.setFont(font)
        self.labelras.setObjectName(_fromUtf8("labelras"))
        self.gridLayout_6.addWidget(self.labelras, 7, 1, 1, 1)
        self.line_16 = QtGui.QFrame(self.layoutWidget_3)
        self.line_16.setFrameShape(QtGui.QFrame.HLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName(_fromUtf8("line_16"))
        self.gridLayout_6.addWidget(self.line_16, 0, 0, 1, 6)
        self.label_36 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_6.addWidget(self.label_36, 3, 0, 5, 1)
        self.labelrr = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelrr.setFont(font)
        self.labelrr.setObjectName(_fromUtf8("labelrr"))
        self.gridLayout_6.addWidget(self.labelrr, 4, 1, 1, 1)
        self.labelrs = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelrs.setFont(font)
        self.labelrs.setObjectName(_fromUtf8("labelrs"))
        self.gridLayout_6.addWidget(self.labelrs, 4, 5, 1, 1)
        self.line_20 = QtGui.QFrame(self.layoutWidget_3)
        self.line_20.setFrameShape(QtGui.QFrame.HLine)
        self.line_20.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_20.setObjectName(_fromUtf8("line_20"))
        self.gridLayout_6.addWidget(self.line_20, 5, 1, 1, 1)
        self.line_18 = QtGui.QFrame(self.layoutWidget_3)
        self.line_18.setFrameShape(QtGui.QFrame.HLine)
        self.line_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_18.setObjectName(_fromUtf8("line_18"))
        self.gridLayout_6.addWidget(self.line_18, 5, 3, 1, 1)
        self.labelrt = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelrt.setFont(font)
        self.labelrt.setObjectName(_fromUtf8("labelrt"))
        self.gridLayout_6.addWidget(self.labelrt, 7, 3, 1, 1)
        self.line_19 = QtGui.QFrame(self.layoutWidget_3)
        self.line_19.setFrameShape(QtGui.QFrame.HLine)
        self.line_19.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_19.setObjectName(_fromUtf8("line_19"))
        self.gridLayout_6.addWidget(self.line_19, 5, 5, 1, 1)
        self.line_21 = QtGui.QFrame(self.layoutWidget_3)
        self.line_21.setFrameShape(QtGui.QFrame.VLine)
        self.line_21.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_21.setObjectName(_fromUtf8("line_21"))
        self.gridLayout_6.addWidget(self.line_21, 3, 2, 5, 1)
        self.line_22 = QtGui.QFrame(self.layoutWidget_3)
        self.line_22.setFrameShape(QtGui.QFrame.HLine)
        self.line_22.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_22.setObjectName(_fromUtf8("line_22"))
        self.gridLayout_6.addWidget(self.line_22, 8, 0, 1, 6)
        self.layoutWidget4 = QtGui.QWidget(self.tab3)
        self.layoutWidget4.setGeometry(QtCore.QRect(60, 300, 501, 41))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_42 = QtGui.QLabel(self.layoutWidget4)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.horizontalLayout.addWidget(self.label_42)
        self.lcdtmh = QtGui.QLCDNumber(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lcdtmh.setFont(font)
        self.lcdtmh.setObjectName(_fromUtf8("lcdtmh"))
        self.horizontalLayout.addWidget(self.lcdtmh)
        spacerItem = QtGui.QSpacerItem(168, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.toolBox.addItem(self.tab3, _fromUtf8(""))
        self.tab4 = QtGui.QWidget()
        self.tab4.setGeometry(QtCore.QRect(0, 0, 671, 367))
        self.tab4.setObjectName(_fromUtf8("tab4"))
        self.layoutWidget_4 = QtGui.QWidget(self.tab4)
        self.layoutWidget_4.setGeometry(QtCore.QRect(0, 30, 661, 151))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.gridLayout_7 = QtGui.QGridLayout(self.layoutWidget_4)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.line_24 = QtGui.QFrame(self.layoutWidget_4)
        self.line_24.setFrameShape(QtGui.QFrame.HLine)
        self.line_24.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_24.setObjectName(_fromUtf8("line_24"))
        self.gridLayout_7.addWidget(self.line_24, 2, 1, 1, 2)
        self.lcds = QtGui.QLCDNumber(self.layoutWidget_4)
        self.lcds.setObjectName(_fromUtf8("lcds"))
        self.gridLayout_7.addWidget(self.lcds, 1, 4, 1, 1)
        self.lcdnhr = QtGui.QLCDNumber(self.layoutWidget_4)
        self.lcdnhr.setObjectName(_fromUtf8("lcdnhr"))
        self.gridLayout_7.addWidget(self.lcdnhr, 4, 1, 1, 1)
        self.line_23 = QtGui.QFrame(self.layoutWidget_4)
        self.line_23.setFrameShape(QtGui.QFrame.VLine)
        self.line_23.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_23.setObjectName(_fromUtf8("line_23"))
        self.gridLayout_7.addWidget(self.line_23, 0, 3, 5, 1)
        self.label_51 = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_51.setFont(font)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout_7.addWidget(self.label_51, 1, 2, 1, 1)
        self.label_43 = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_7.addWidget(self.label_43, 0, 4, 1, 1)
        self.label_44 = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_7.addWidget(self.label_44, 0, 0, 5, 1)
        self.label_52 = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_52.setFont(font)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.gridLayout_7.addWidget(self.label_52, 1, 5, 1, 1)
        self.label_49 = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_49.setFont(font)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_7.addWidget(self.label_49, 4, 2, 1, 1)
        self.label_47 = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_7.addWidget(self.label_47, 3, 1, 1, 1)
        self.label_48 = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_7.addWidget(self.label_48, 3, 2, 1, 1)
        self.label_50 = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_7.addWidget(self.label_50, 0, 5, 1, 1)
        self.label_46 = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_7.addWidget(self.label_46, 0, 2, 1, 1)
        self.label_45 = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_7.addWidget(self.label_45, 0, 1, 1, 1)
        self.lcdj = QtGui.QLCDNumber(self.layoutWidget_4)
        self.lcdj.setObjectName(_fromUtf8("lcdj"))
        self.gridLayout_7.addWidget(self.lcdj, 1, 1, 1, 1)
        self.line_25 = QtGui.QFrame(self.layoutWidget_4)
        self.line_25.setFrameShape(QtGui.QFrame.HLine)
        self.line_25.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_25.setObjectName(_fromUtf8("line_25"))
        self.gridLayout_7.addWidget(self.line_25, 2, 4, 1, 2)
        self.layoutWidget_5 = QtGui.QWidget(self.tab4)
        self.layoutWidget_5.setGeometry(QtCore.QRect(0, 190, 661, 151))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.gridLayout_8 = QtGui.QGridLayout(self.layoutWidget_5)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.lcdrtet = QtGui.QLCDNumber(self.layoutWidget_5)
        self.lcdrtet.setObjectName(_fromUtf8("lcdrtet"))
        self.gridLayout_8.addWidget(self.lcdrtet, 2, 5, 1, 1)
        self.label_56 = QtGui.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.gridLayout_8.addWidget(self.label_56, 4, 3, 1, 1)
        self.label_59 = QtGui.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_59.setFont(font)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.gridLayout_8.addWidget(self.label_59, 1, 1, 1, 1)
        self.label_55 = QtGui.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.gridLayout_8.addWidget(self.label_55, 4, 1, 1, 1)
        self.label_58 = QtGui.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_58.setFont(font)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.gridLayout_8.addWidget(self.label_58, 1, 3, 1, 1)
        self.label_57 = QtGui.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_57.setFont(font)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.gridLayout_8.addWidget(self.label_57, 1, 7, 1, 1)
        self.label_63 = QtGui.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_63.setFont(font)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.gridLayout_8.addWidget(self.label_63, 4, 5, 1, 1)
        self.label_62 = QtGui.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_62.setFont(font)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.gridLayout_8.addWidget(self.label_62, 1, 5, 1, 1)
        self.line_5 = QtGui.QFrame(self.layoutWidget_5)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout_8.addWidget(self.line_5, 0, 0, 1, 8)
        self.label_60 = QtGui.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_60.setFont(font)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.gridLayout_8.addWidget(self.label_60, 1, 0, 5, 1)
        self.lcdrf = QtGui.QLCDNumber(self.layoutWidget_5)
        self.lcdrf.setObjectName(_fromUtf8("lcdrf"))
        self.gridLayout_8.addWidget(self.lcdrf, 2, 3, 1, 1)
        self.lcdff = QtGui.QLCDNumber(self.layoutWidget_5)
        self.lcdff.setObjectName(_fromUtf8("lcdff"))
        self.gridLayout_8.addWidget(self.lcdff, 2, 1, 1, 1)
        self.line_26 = QtGui.QFrame(self.layoutWidget_5)
        self.line_26.setFrameShape(QtGui.QFrame.HLine)
        self.line_26.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_26.setObjectName(_fromUtf8("line_26"))
        self.gridLayout_8.addWidget(self.line_26, 3, 1, 1, 7)
        self.line_30 = QtGui.QFrame(self.layoutWidget_5)
        self.line_30.setFrameShape(QtGui.QFrame.VLine)
        self.line_30.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_30.setObjectName(_fromUtf8("line_30"))
        self.gridLayout_8.addWidget(self.line_30, 4, 4, 2, 1)
        self.lcdt = QtGui.QLCDNumber(self.layoutWidget_5)
        self.lcdt.setObjectName(_fromUtf8("lcdt"))
        self.gridLayout_8.addWidget(self.lcdt, 2, 7, 1, 1)
        self.line_28 = QtGui.QFrame(self.layoutWidget_5)
        self.line_28.setFrameShape(QtGui.QFrame.VLine)
        self.line_28.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_28.setObjectName(_fromUtf8("line_28"))
        self.gridLayout_8.addWidget(self.line_28, 4, 2, 2, 1)
        self.line_27 = QtGui.QFrame(self.layoutWidget_5)
        self.line_27.setFrameShape(QtGui.QFrame.VLine)
        self.line_27.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_27.setObjectName(_fromUtf8("line_27"))
        self.gridLayout_8.addWidget(self.line_27, 1, 2, 2, 1)
        self.line_29 = QtGui.QFrame(self.layoutWidget_5)
        self.line_29.setFrameShape(QtGui.QFrame.VLine)
        self.line_29.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_29.setObjectName(_fromUtf8("line_29"))
        self.gridLayout_8.addWidget(self.line_29, 1, 4, 2, 1)
        self.line_31 = QtGui.QFrame(self.layoutWidget_5)
        self.line_31.setFrameShape(QtGui.QFrame.VLine)
        self.line_31.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_31.setObjectName(_fromUtf8("line_31"))
        self.gridLayout_8.addWidget(self.line_31, 1, 6, 2, 1)
        self.line_32 = QtGui.QFrame(self.layoutWidget_5)
        self.line_32.setFrameShape(QtGui.QFrame.VLine)
        self.line_32.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_32.setObjectName(_fromUtf8("line_32"))
        self.gridLayout_8.addWidget(self.line_32, 4, 6, 2, 1)
        self.labeltipo = QtGui.QLabel(self.layoutWidget_5)
        self.labeltipo.setObjectName(_fromUtf8("labeltipo"))
        self.gridLayout_8.addWidget(self.labeltipo, 5, 1, 1, 1)
        self.labelcbh = QtGui.QLabel(self.layoutWidget_5)
        self.labelcbh.setObjectName(_fromUtf8("labelcbh"))
        self.gridLayout_8.addWidget(self.labelcbh, 5, 3, 1, 1)
        self.labelcbm = QtGui.QLabel(self.layoutWidget_5)
        self.labelcbm.setObjectName(_fromUtf8("labelcbm"))
        self.gridLayout_8.addWidget(self.labelcbm, 5, 5, 1, 1)
        self.toolBox.addItem(self.tab4, _fromUtf8(""))
        self.labelNombre = QtGui.QLabel(self.centralWidget)
        self.labelNombre.setGeometry(QtCore.QRect(10, 0, 301, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelNombre.setFont(font)
        self.labelNombre.setObjectName(_fromUtf8("labelNombre"))
        self.labelRun = QtGui.QLabel(self.centralWidget)
        self.labelRun.setGeometry(QtCore.QRect(320, 0, 201, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelRun.setFont(font)
        self.labelRun.setObjectName(_fromUtf8("labelRun"))
        self.labelFecha = QtGui.QLabel(self.centralWidget)
        self.labelFecha.setGeometry(QtCore.QRect(530, 0, 201, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelFecha.setFont(font)
        self.labelFecha.setObjectName(_fromUtf8("labelFecha"))
        vistaEvocal.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(vistaEvocal)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 690, 25))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        vistaEvocal.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(vistaEvocal)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        vistaEvocal.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(vistaEvocal)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        vistaEvocal.setStatusBar(self.statusBar)

        self.retranslateUi(vistaEvocal)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(vistaEvocal)

    def retranslateUi(self, vistaEvocal):
        vistaEvocal.setWindowTitle(_translate("vistaEvocal", "EVALUACION VOCAL", None))
        self.label_2.setText(_translate("vistaEvocal", "Funcional", None))
        self.labelFIsica.setText(_translate("vistaEvocal", "Física", None))
        self.label_4.setText(_translate("vistaEvocal", "Emocional", None))
        self.label_3.setText(_translate("vistaEvocal", "TOTAL", None))
        self.label.setText(_translate("vistaEvocal", "Puntaje VHI", None))
        self.label_7.setText(_translate("vistaEvocal", "Modo respiratrio\n"
"en reposo", None))
        self.label_10.setText(_translate("vistaEvocal", "Número de inspiraciones\n"
"durante conteo", None))
        self.label_5.setText(_translate("vistaEvocal", "Tipo respiratrio\n"
"en reposo", None))
        self.label_9.setText(_translate("vistaEvocal", "Coordinación\n"
"fono-respiratoria", None))
        self.label_11.setText(_translate("vistaEvocal", "Tiempo máximo\n"
"de fonación", None))
        self.label_13.setText(_translate("vistaEvocal", "Tiempo máximo\n"
"de espiración", None))
        self.label_6.setText(_translate("vistaEvocal", "Tipo respiratrio\n"
"en fonación", None))
        self.label_8.setText(_translate("vistaEvocal", "Modo respiratrio\n"
"en fonación", None))
        self.labelmrr.setText(_translate("vistaEvocal", "predominio costal alto", None))
        self.label_53.setText(_translate("vistaEvocal", "labeltrf", None))
        self.labeltrr.setText(_translate("vistaEvocal", "labeltrr", None))
        self.label_12.setText(_translate("vistaEvocal", "Indice s/a", None))
        self.labelmrf.setText(_translate("vistaEvocal", "predominio bucal alto", None))
        self.labelcrf.setText(_translate("vistaEvocal", "labelcrf", None))
        self.label_14.setText(_translate("vistaEvocal", "Apoyo respiratorio", None))
        self.labelar.setText(_translate("vistaEvocal", "TextLabel", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tab1), _translate("vistaEvocal", "Principal", None))
        self.label_23.setText(_translate("vistaEvocal", "Suprahioidea", None))
        self.label_21.setText(_translate("vistaEvocal", "General", None))
        self.label_22.setText(_translate("vistaEvocal", "Infrahioidea", None))
        self.label_20.setText(_translate("vistaEvocal", "Cervical", None))
        self.label_25.setText(_translate("vistaEvocal", "Cintura escapular", None))
        self.label_26.setText(_translate("vistaEvocal", "Altura laringea", None))
        self.labeltal.setText(_translate("vistaEvocal", "Desplacamiento lateral hacia izquierda", None))
        self.labeltg.setText(_translate("vistaEvocal", "TextLabel", None))
        self.label_24.setText(_translate("vistaEvocal", "TONICIDAD", None))
        self.labelti.setText(_translate("vistaEvocal", "TextLabel", None))
        self.labelts.setText(_translate("vistaEvocal", "TextLabel", None))
        self.labeltce.setText(_translate("vistaEvocal", "TextLabel", None))
        self.labeltc.setText(_translate("vistaEvocal", "TextLabel", None))
        self.label_27.setText(_translate("vistaEvocal", "Observaciones", None))
        self.labelppp3.setText(_translate("vistaEvocal", "TextLabel", None))
        self.label_16.setText(_translate("vistaEvocal", "Lateral", None))
        self.label_17.setText(_translate("vistaEvocal", "Posterior", None))
        self.labelppl2.setText(_translate("vistaEvocal", "TextLabel", None))
        self.label_19.setText(_translate("vistaEvocal", "Planos", None))
        self.label_18.setText(_translate("vistaEvocal", "POSTURA", None))
        self.labelppf3.setText(_translate("vistaEvocal", "TextLabel", None))
        self.labelppp1.setText(_translate("vistaEvocal", "Hacia izquierda", None))
        self.label_15.setText(_translate("vistaEvocal", "Frontal", None))
        self.labelppp2.setText(_translate("vistaEvocal", "TextLabel", None))
        self.labelppf2.setText(_translate("vistaEvocal", "TextLabel", None))
        self.labelppl1.setText(_translate("vistaEvocal", "Rectificación cervical", None))
        self.labelppl3.setText(_translate("vistaEvocal", "TextLabel", None))
        self.labelppf1.setText(_translate("vistaEvocal", "Hacia izquierda", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tab2), _translate("vistaEvocal", "Postura y tonicidad", None))
        self.label_28.setText(_translate("vistaEvocal", "Punta\n"
"de pies", None))
        self.label_31.setText(_translate("vistaEvocal", "Extensión\n"
"del codo", None))
        self.label_30.setText(_translate("vistaEvocal", "Pulgar hacia\n"
"antebrazo", None))
        self.label_32.setText(_translate("vistaEvocal", "Dedos en\n"
"extensión", None))
        self.label_33.setText(_translate("vistaEvocal", "Rodillas en\n"
"hiperextensión", None))
        self.label_34.setText(_translate("vistaEvocal", "Puntaje Total", None))
        self.label_29.setText(_translate("vistaEvocal", "Hiperlaxitud", None))
        self.label_40.setText(_translate("vistaEvocal", "Tensión", None))
        self.label_41.setText(_translate("vistaEvocal", "Inestabilidad", None))
        self.label_38.setText(_translate("vistaEvocal", "Aspereza", None))
        self.label_39.setText(_translate("vistaEvocal", "Astenia", None))
        self.label_37.setText(_translate("vistaEvocal", "Ronquera", None))
        self.label_35.setText(_translate("vistaEvocal", "Soplicidad", None))
        self.labelri.setText(_translate("vistaEvocal", "TextLabel", None))
        self.labelra.setText(_translate("vistaEvocal", "moderado", None))
        self.labelras.setText(_translate("vistaEvocal", "TextLabel", None))
        self.label_36.setText(_translate("vistaEvocal", "RASATI", None))
        self.labelrr.setText(_translate("vistaEvocal", "moderado", None))
        self.labelrs.setText(_translate("vistaEvocal", "moderado", None))
        self.labelrt.setText(_translate("vistaEvocal", "TextLabel", None))
        self.label_42.setText(_translate("vistaEvocal", "Tono medio hablado", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tab3), _translate("vistaEvocal", "Hiperlaxitud, RASATI y tono media hablado", None))
        self.label_51.setText(_translate("vistaEvocal", "< 1,040 %", None))
        self.label_43.setText(_translate("vistaEvocal", "Shimmer local\n"
"obtenido", None))
        self.label_44.setText(_translate("vistaEvocal", "Parámetros\n"
"acústicos", None))
        self.label_52.setText(_translate("vistaEvocal", "< 3,810 %", None))
        self.label_49.setText(_translate("vistaEvocal", "> 20 dB", None))
        self.label_47.setText(_translate("vistaEvocal", "NHR obtenido", None))
        self.label_48.setText(_translate("vistaEvocal", "Rango NHR\n"
"esperado (Praat)", None))
        self.label_50.setText(_translate("vistaEvocal", "Rango Shimmer\n"
"local esperado (Praat)", None))
        self.label_46.setText(_translate("vistaEvocal", "Rango Jitter local\n"
"esperado (Praat)", None))
        self.label_45.setText(_translate("vistaEvocal", "Jitter local\n"
"obtenido", None))
        self.label_56.setText(_translate("vistaEvocal", "Clasificación vocal\n"
"hombre", None))
        self.label_59.setText(_translate("vistaEvocal", "Frecuencia\n"
"fundamenta", None))
        self.label_55.setText(_translate("vistaEvocal", "Tipo Cantante", None))
        self.label_58.setText(_translate("vistaEvocal", "Rango\n"
"frecuencial", None))
        self.label_57.setText(_translate("vistaEvocal", "Tesitura", None))
        self.label_63.setText(_translate("vistaEvocal", "Clasificación vocal\n"
"mujer", None))
        self.label_62.setText(_translate("vistaEvocal", "Rango tonal\n"
"extensión tonal", None))
        self.label_60.setText(_translate("vistaEvocal", "Voz\n"
"cantada", None))
        self.labeltipo.setText(_translate("vistaEvocal", "Cantante popular", None))
        self.labelcbh.setText(_translate("vistaEvocal", "Barítono", None))
        self.labelcbm.setText(_translate("vistaEvocal", "Mezzosoprano", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tab4), _translate("vistaEvocal", "Parámetros acústicos y voz cantada", None))
        self.labelNombre.setText(_translate("vistaEvocal", "TextLabel", None))
        self.labelRun.setText(_translate("vistaEvocal", "TextLabel", None))
        self.labelFecha.setText(_translate("vistaEvocal", "TextLabel", None))

