# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'consultaSintomatologia.ui'
#
# Created: Wed Feb 11 16:22:47 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_consultaSintoma(object):
    def setupUi(self, consultaSintoma):
        consultaSintoma.setObjectName(_fromUtf8("consultaSintoma"))
        consultaSintoma.resize(777, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("./img/aav50.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        consultaSintoma.setWindowIcon(icon)
        self.layoutWidget = QtGui.QWidget(consultaSintoma)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 194, 761, 131))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.line_2 = QtGui.QFrame(self.layoutWidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_2.addWidget(self.line_2, 3, 0, 1, 5)
        self.los3 = QtGui.QLabel(self.layoutWidget)
        self.los3.setObjectName(_fromUtf8("los3"))
        self.gridLayout_2.addWidget(self.los3, 1, 3, 1, 1)
        self.los4 = QtGui.QLabel(self.layoutWidget)
        self.los4.setObjectName(_fromUtf8("los4"))
        self.gridLayout_2.addWidget(self.los4, 1, 4, 1, 1)
        self.los1 = QtGui.QLabel(self.layoutWidget)
        self.los1.setObjectName(_fromUtf8("los1"))
        self.gridLayout_2.addWidget(self.los1, 1, 1, 1, 1)
        self.los2 = QtGui.QLabel(self.layoutWidget)
        self.los2.setObjectName(_fromUtf8("los2"))
        self.gridLayout_2.addWidget(self.los2, 1, 2, 1, 1)
        self.dos1 = QtGui.QTextEdit(self.layoutWidget)
        self.dos1.setObjectName(_fromUtf8("dos1"))
        self.gridLayout_2.addWidget(self.dos1, 2, 1, 1, 1)
        self.dos4 = QtGui.QTextEdit(self.layoutWidget)
        self.dos4.setObjectName(_fromUtf8("dos4"))
        self.gridLayout_2.addWidget(self.dos4, 2, 4, 1, 1)
        self.dos3 = QtGui.QTextEdit(self.layoutWidget)
        self.dos3.setObjectName(_fromUtf8("dos3"))
        self.gridLayout_2.addWidget(self.dos3, 2, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 4)
        self.dos2 = QtGui.QTextEdit(self.layoutWidget)
        self.dos2.setObjectName(_fromUtf8("dos2"))
        self.gridLayout_2.addWidget(self.dos2, 2, 2, 1, 1)
        self.layoutWidget_3 = QtGui.QWidget(consultaSintoma)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 420, 761, 131))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget_3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.dcav1 = QtGui.QTextEdit(self.layoutWidget_3)
        self.dcav1.setObjectName(_fromUtf8("dcav1"))
        self.gridLayout_3.addWidget(self.dcav1, 3, 1, 1, 1)
        self.line_3 = QtGui.QFrame(self.layoutWidget_3)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_3.addWidget(self.line_3, 0, 0, 1, 5)
        self.dcav4 = QtGui.QTextEdit(self.layoutWidget_3)
        self.dcav4.setObjectName(_fromUtf8("dcav4"))
        self.gridLayout_3.addWidget(self.dcav4, 3, 4, 1, 1)
        self.dcav3 = QtGui.QTextEdit(self.layoutWidget_3)
        self.dcav3.setObjectName(_fromUtf8("dcav3"))
        self.gridLayout_3.addWidget(self.dcav3, 3, 3, 1, 1)
        self.dcav2 = QtGui.QTextEdit(self.layoutWidget_3)
        self.dcav2.setObjectName(_fromUtf8("dcav2"))
        self.gridLayout_3.addWidget(self.dcav2, 3, 2, 1, 1)
        self.lcav1 = QtGui.QLabel(self.layoutWidget_3)
        self.lcav1.setObjectName(_fromUtf8("lcav1"))
        self.gridLayout_3.addWidget(self.lcav1, 2, 1, 1, 1)
        self.lcav2 = QtGui.QLabel(self.layoutWidget_3)
        self.lcav2.setObjectName(_fromUtf8("lcav2"))
        self.gridLayout_3.addWidget(self.lcav2, 2, 2, 1, 1)
        self.lcav3 = QtGui.QLabel(self.layoutWidget_3)
        self.lcav3.setObjectName(_fromUtf8("lcav3"))
        self.gridLayout_3.addWidget(self.lcav3, 2, 3, 1, 1)
        self.lcav4 = QtGui.QLabel(self.layoutWidget_3)
        self.lcav4.setObjectName(_fromUtf8("lcav4"))
        self.gridLayout_3.addWidget(self.lcav4, 2, 4, 1, 1)
        self.label_19 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_3.addWidget(self.label_19, 1, 1, 1, 4)
        self.label_9 = QtGui.QLabel(consultaSintoma)
        self.label_9.setGeometry(QtCore.QRect(10, 570, 131, 17))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(consultaSintoma)
        self.label_10.setGeometry(QtCore.QRect(20, 20, 67, 17))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.nombrep = QtGui.QLabel(consultaSintoma)
        self.nombrep.setGeometry(QtCore.QRect(90, 10, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.nombrep.setFont(font)
        self.nombrep.setObjectName(_fromUtf8("nombrep"))
        self.fecha = QtGui.QLabel(consultaSintoma)
        self.fecha.setGeometry(QtCore.QRect(496, 20, 101, 21))
        self.fecha.setText(_fromUtf8(""))
        self.fecha.setObjectName(_fromUtf8("fecha"))
        self.layoutWidget1 = QtGui.QWidget(consultaSintoma)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 50, 761, 131))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.dsv3 = QtGui.QTextEdit(self.layoutWidget1)
        self.dsv3.setObjectName(_fromUtf8("dsv3"))
        self.gridLayout.addWidget(self.dsv3, 2, 5, 1, 1)
        self.dsv1 = QtGui.QTextEdit(self.layoutWidget1)
        self.dsv1.setObjectName(_fromUtf8("dsv1"))
        self.gridLayout.addWidget(self.dsv1, 2, 1, 1, 1)
        self.line_4 = QtGui.QFrame(self.layoutWidget1)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout.addWidget(self.line_4, 1, 2, 2, 1)
        self.lsv2 = QtGui.QLabel(self.layoutWidget1)
        self.lsv2.setObjectName(_fromUtf8("lsv2"))
        self.gridLayout.addWidget(self.lsv2, 1, 3, 1, 1)
        self.lsv4 = QtGui.QLabel(self.layoutWidget1)
        self.lsv4.setObjectName(_fromUtf8("lsv4"))
        self.gridLayout.addWidget(self.lsv4, 1, 7, 1, 1)
        self.lsv3 = QtGui.QLabel(self.layoutWidget1)
        self.lsv3.setObjectName(_fromUtf8("lsv3"))
        self.gridLayout.addWidget(self.lsv3, 1, 5, 1, 1)
        self.line = QtGui.QFrame(self.layoutWidget1)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 3, 0, 1, 6)
        self.dsv2 = QtGui.QTextEdit(self.layoutWidget1)
        self.dsv2.setObjectName(_fromUtf8("dsv2"))
        self.gridLayout.addWidget(self.dsv2, 2, 3, 1, 1)
        self.dsv4 = QtGui.QTextEdit(self.layoutWidget1)
        self.dsv4.setObjectName(_fromUtf8("dsv4"))
        self.gridLayout.addWidget(self.dsv4, 2, 7, 1, 1)
        self.line_6 = QtGui.QFrame(self.layoutWidget1)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.gridLayout.addWidget(self.line_6, 1, 6, 2, 1)
        self.line_5 = QtGui.QFrame(self.layoutWidget1)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout.addWidget(self.line_5, 1, 4, 2, 1)
        self.lsv1 = QtGui.QLabel(self.layoutWidget1)
        self.lsv1.setObjectName(_fromUtf8("lsv1"))
        self.gridLayout.addWidget(self.lsv1, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 1, 1, 7)
        self.apellidop = QtGui.QLabel(consultaSintoma)
        self.apellidop.setGeometry(QtCore.QRect(340, 10, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.apellidop.setFont(font)
        self.apellidop.setObjectName(_fromUtf8("apellidop"))
        self.lcdhqd = QtGui.QLCDNumber(consultaSintoma)
        self.lcdhqd.setGeometry(QtCore.QRect(150, 562, 71, 31))
        self.lcdhqd.setObjectName(_fromUtf8("lcdhqd"))
        self.lfecha = QtGui.QLabel(consultaSintoma)
        self.lfecha.setGeometry(QtCore.QRect(650, 10, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lfecha.setFont(font)
        self.lfecha.setObjectName(_fromUtf8("lfecha"))
        self.widget = QtGui.QWidget(consultaSintoma)
        self.widget.setGeometry(QtCore.QRect(10, 331, 761, 81))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.tamg = QtGui.QTextEdit(self.widget)
        self.tamg.setObjectName(_fromUtf8("tamg"))
        self.horizontalLayout.addWidget(self.tamg)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_6 = QtGui.QLabel(self.widget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.tmqc = QtGui.QTextEdit(self.widget)
        self.tmqc.setObjectName(_fromUtf8("tmqc"))
        self.horizontalLayout_2.addWidget(self.tmqc)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)

        self.retranslateUi(consultaSintoma)
        QtCore.QMetaObject.connectSlotsByName(consultaSintoma)

    def retranslateUi(self, consultaSintoma):
        consultaSintoma.setWindowTitle(_translate("consultaSintoma", "Sintomatología y Conductas", None))
        self.los3.setText(_translate("consultaSintoma", "Pérdidas anteriores de\n"
"la voz", None))
        self.los4.setText(_translate("consultaSintoma", "Pérdidas anteriores de\n"
"la voz", None))
        self.los1.setText(_translate("consultaSintoma", "Pérdidas anteriores de\n"
"la voz", None))
        self.los2.setText(_translate("consultaSintoma", "Pérdidas anteriores de\n"
"la voz", None))
        self.label_2.setText(_translate("consultaSintoma", "OTROS SINTOMAS", None))
        self.lcav1.setText(_translate("consultaSintoma", "Consumo de alimentos\n"
"condimentados", None))
        self.lcav2.setText(_translate("consultaSintoma", "Consumo de alimentos\n"
"condimentados", None))
        self.lcav3.setText(_translate("consultaSintoma", "Consumo de alimentos\n"
"condimentados", None))
        self.lcav4.setText(_translate("consultaSintoma", "Consumo de alimentos\n"
"condimentados", None))
        self.label_19.setText(_translate("consultaSintoma", "Conductas de abuso vocal", None))
        self.label_9.setText(_translate("consultaSintoma", "Horas que duerme:", None))
        self.label_10.setText(_translate("consultaSintoma", "Paciente:", None))
        self.nombrep.setText(_translate("consultaSintoma", "nombre", None))
        self.lsv2.setText(_translate("consultaSintoma", "Sensación de cuerpo\n"
"extraño", None))
        self.lsv4.setText(_translate("consultaSintoma", "Sensación de cuerpo\n"
"extraño", None))
        self.lsv3.setText(_translate("consultaSintoma", "Sensación de cuerpo\n"
"extraño", None))
        self.lsv1.setText(_translate("consultaSintoma", "Sensación de cuerpo \n"
"extraño", None))
        self.label.setText(_translate("consultaSintoma", "SINTOMAS VOCALES RELEVANTES", None))
        self.apellidop.setText(_translate("consultaSintoma", "run", None))
        self.lfecha.setText(_translate("consultaSintoma", "fecha", None))
        self.label_5.setText(_translate("consultaSintoma", "Antecedentes\n"
"médicos\n"
"generales:", None))
        self.label_6.setText(_translate("consultaSintoma", "Medicamentos\n"
"que consume:", None))

