# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'evaluacionvocal.ui'
#
# Created: Tue Feb 10 21:21:30 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_EvaluacionVocal(object):
    def setupUi(self, EvaluacionVocal):
        EvaluacionVocal.setObjectName(_fromUtf8("EvaluacionVocal"))
        EvaluacionVocal.resize(535, 576)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("./img/aav.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        EvaluacionVocal.setWindowIcon(icon)
        self.centralWidget = QtGui.QWidget(EvaluacionVocal)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.pushButton = QtGui.QPushButton(self.centralWidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 480, 99, 27))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("./img/edit16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.toolBox = QtGui.QToolBox(self.centralWidget)
        self.toolBox.setGeometry(QtCore.QRect(20, 30, 521, 441))
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.tab1 = QtGui.QWidget()
        self.tab1.setGeometry(QtCore.QRect(0, 0, 521, 317))
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.layoutWidget = QtGui.QWidget(self.tab1)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 491, 62))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 1, 2, 1)
        self.labelFIsica = QtGui.QLabel(self.layoutWidget)
        self.labelFIsica.setObjectName(_fromUtf8("labelFIsica"))
        self.gridLayout.addWidget(self.labelFIsica, 0, 2, 2, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 3, 2, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 4, 1, 1)
        self.lcdTotal = QtGui.QLCDNumber(self.layoutWidget)
        self.lcdTotal.setObjectName(_fromUtf8("lcdTotal"))
        self.gridLayout.addWidget(self.lcdTotal, 1, 4, 2, 1)
        self.spinFuncional = QtGui.QSpinBox(self.layoutWidget)
        self.spinFuncional.setMaximum(40)
        self.spinFuncional.setObjectName(_fromUtf8("spinFuncional"))
        self.gridLayout.addWidget(self.spinFuncional, 2, 1, 1, 1)
        self.spinFisica = QtGui.QSpinBox(self.layoutWidget)
        self.spinFisica.setMaximum(40)
        self.spinFisica.setObjectName(_fromUtf8("spinFisica"))
        self.gridLayout.addWidget(self.spinFisica, 2, 2, 1, 1)
        self.spinEmocional = QtGui.QSpinBox(self.layoutWidget)
        self.spinEmocional.setMaximum(40)
        self.spinEmocional.setObjectName(_fromUtf8("spinEmocional"))
        self.gridLayout.addWidget(self.spinEmocional, 2, 3, 1, 1)
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 3, 1)
        self.layoutWidget1 = QtGui.QWidget(self.tab1)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 80, 501, 225))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.comboTRR = QtGui.QComboBox(self.layoutWidget1)
        self.comboTRR.setObjectName(_fromUtf8("comboTRR"))
        self.comboTRR.addItem(_fromUtf8(""))
        self.comboTRR.addItem(_fromUtf8(""))
        self.comboTRR.addItem(_fromUtf8(""))
        self.comboTRR.addItem(_fromUtf8(""))
        self.comboTRR.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboTRR, 0, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget1)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 2)
        self.label_14 = QtGui.QLabel(self.layoutWidget1)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 5, 3, 1, 1)
        self.spinTMF = QtGui.QSpinBox(self.layoutWidget1)
        self.spinTMF.setMinimum(1)
        self.spinTMF.setMaximum(40)
        self.spinTMF.setObjectName(_fromUtf8("spinTMF"))
        self.gridLayout_2.addWidget(self.spinTMF, 3, 2, 1, 1)
        self.comboMRR = QtGui.QComboBox(self.layoutWidget1)
        self.comboMRR.setObjectName(_fromUtf8("comboMRR"))
        self.comboMRR.addItem(_fromUtf8(""))
        self.comboMRR.addItem(_fromUtf8(""))
        self.comboMRR.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboMRR, 1, 2, 1, 1)
        self.spinTME = QtGui.QSpinBox(self.layoutWidget1)
        self.spinTME.setMinimum(1)
        self.spinTME.setMaximum(40)
        self.spinTME.setObjectName(_fromUtf8("spinTME"))
        self.gridLayout_2.addWidget(self.spinTME, 3, 5, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget1)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 2, 3, 1, 2)
        self.lcdNumber = QtGui.QLCDNumber(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.gridLayout_2.addWidget(self.lcdNumber, 5, 2, 1, 1)
        self.comboCFR = QtGui.QComboBox(self.layoutWidget1)
        self.comboCFR.setObjectName(_fromUtf8("comboCFR"))
        self.comboCFR.addItem(_fromUtf8(""))
        self.comboCFR.addItem(_fromUtf8(""))
        self.comboCFR.addItem(_fromUtf8(""))
        self.comboCFR.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboCFR, 2, 2, 1, 1)
        self.spinNIDC = QtGui.QSpinBox(self.layoutWidget1)
        self.spinNIDC.setMinimum(1)
        self.spinNIDC.setMaximum(40)
        self.spinNIDC.setObjectName(_fromUtf8("spinNIDC"))
        self.gridLayout_2.addWidget(self.spinNIDC, 2, 5, 1, 1)
        self.comboAR = QtGui.QComboBox(self.layoutWidget1)
        self.comboAR.setObjectName(_fromUtf8("comboAR"))
        self.comboAR.addItem(_fromUtf8(""))
        self.comboAR.addItem(_fromUtf8(""))
        self.comboAR.addItem(_fromUtf8(""))
        self.comboAR.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboAR, 5, 4, 1, 2)
        self.label_5 = QtGui.QLabel(self.layoutWidget1)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 2)
        self.label_9 = QtGui.QLabel(self.layoutWidget1)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 2)
        self.label_11 = QtGui.QLabel(self.layoutWidget1)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 3, 0, 1, 2)
        self.label_12 = QtGui.QLabel(self.layoutWidget1)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 5, 0, 1, 2)
        self.label_13 = QtGui.QLabel(self.layoutWidget1)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 3, 3, 1, 2)
        self.comboTRF = QtGui.QComboBox(self.layoutWidget1)
        self.comboTRF.setObjectName(_fromUtf8("comboTRF"))
        self.comboTRF.addItem(_fromUtf8(""))
        self.comboTRF.addItem(_fromUtf8(""))
        self.comboTRF.addItem(_fromUtf8(""))
        self.comboTRF.addItem(_fromUtf8(""))
        self.comboTRF.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboTRF, 0, 5, 1, 1)
        self.comboBox_2 = QtGui.QComboBox(self.layoutWidget1)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.comboBox_2, 1, 5, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget1)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 3, 1, 2)
        self.label_8 = QtGui.QLabel(self.layoutWidget1)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 1, 3, 1, 2)
        self.toolBox.addItem(self.tab1, _fromUtf8(""))
        self.tab2 = QtGui.QWidget()
        self.tab2.setGeometry(QtCore.QRect(0, 0, 521, 317))
        self.tab2.setObjectName(_fromUtf8("tab2"))
        self.line = QtGui.QFrame(self.tab2)
        self.line.setGeometry(QtCore.QRect(0, 150, 361, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.layoutWidget2 = QtGui.QWidget(self.tab2)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 160, 361, 141))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_23 = QtGui.QLabel(self.layoutWidget2)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_4.addWidget(self.label_23, 0, 3, 1, 1)
        self.label_21 = QtGui.QLabel(self.layoutWidget2)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_4.addWidget(self.label_21, 0, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.layoutWidget2)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_4.addWidget(self.label_22, 0, 2, 1, 1)
        self.label_20 = QtGui.QLabel(self.layoutWidget2)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_4.addWidget(self.label_20, 2, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.layoutWidget2)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_4.addWidget(self.label_25, 2, 2, 1, 1)
        self.label_26 = QtGui.QLabel(self.layoutWidget2)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_4.addWidget(self.label_26, 2, 3, 1, 1)
        self.label_24 = QtGui.QLabel(self.layoutWidget2)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_4.addWidget(self.label_24, 1, 0, 3, 1)
        self.cTonG = QtGui.QComboBox(self.layoutWidget2)
        self.cTonG.setObjectName(_fromUtf8("cTonG"))
        self.cTonG.addItem(_fromUtf8(""))
        self.cTonG.addItem(_fromUtf8(""))
        self.cTonG.addItem(_fromUtf8(""))
        self.cTonG.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.cTonG, 1, 1, 1, 1)
        self.cTonI = QtGui.QComboBox(self.layoutWidget2)
        self.cTonI.setObjectName(_fromUtf8("cTonI"))
        self.cTonI.addItem(_fromUtf8(""))
        self.cTonI.addItem(_fromUtf8(""))
        self.cTonI.addItem(_fromUtf8(""))
        self.cTonI.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.cTonI, 1, 2, 1, 1)
        self.cTonS = QtGui.QComboBox(self.layoutWidget2)
        self.cTonS.setObjectName(_fromUtf8("cTonS"))
        self.cTonS.addItem(_fromUtf8(""))
        self.cTonS.addItem(_fromUtf8(""))
        self.cTonS.addItem(_fromUtf8(""))
        self.cTonS.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.cTonS, 1, 3, 1, 1)
        self.cTonC = QtGui.QComboBox(self.layoutWidget2)
        self.cTonC.setObjectName(_fromUtf8("cTonC"))
        self.cTonC.addItem(_fromUtf8(""))
        self.cTonC.addItem(_fromUtf8(""))
        self.cTonC.addItem(_fromUtf8(""))
        self.cTonC.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.cTonC, 3, 1, 1, 1)
        self.cTonCE = QtGui.QComboBox(self.layoutWidget2)
        self.cTonCE.setObjectName(_fromUtf8("cTonCE"))
        self.cTonCE.addItem(_fromUtf8(""))
        self.cTonCE.addItem(_fromUtf8(""))
        self.cTonCE.addItem(_fromUtf8(""))
        self.cTonCE.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.cTonCE, 3, 2, 1, 1)
        self.cTonAL = QtGui.QComboBox(self.layoutWidget2)
        self.cTonAL.setObjectName(_fromUtf8("cTonAL"))
        self.cTonAL.addItem(_fromUtf8(""))
        self.cTonAL.addItem(_fromUtf8(""))
        self.cTonAL.addItem(_fromUtf8(""))
        self.cTonAL.addItem(_fromUtf8(""))
        self.cTonAL.addItem(_fromUtf8(""))
        self.cTonAL.addItem(_fromUtf8(""))
        self.cTonAL.addItem(_fromUtf8(""))
        self.cTonAL.addItem(_fromUtf8(""))
        self.cTonAL.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.cTonAL, 3, 3, 1, 1)
        self.label_27 = QtGui.QLabel(self.tab2)
        self.label_27.setGeometry(QtCore.QRect(390, 0, 111, 20))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.observacionesPyT = QtGui.QTextEdit(self.tab2)
        self.observacionesPyT.setGeometry(QtCore.QRect(370, 30, 141, 271))
        self.observacionesPyT.setObjectName(_fromUtf8("observacionesPyT"))
        self.layoutWidget3 = QtGui.QWidget(self.tab2)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 0, 361, 151))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_19 = QtGui.QLabel(self.layoutWidget3)
        self.label_19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_3.addWidget(self.label_19, 0, 1, 1, 3)
        self.label_15 = QtGui.QLabel(self.layoutWidget3)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_3.addWidget(self.label_15, 1, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.layoutWidget3)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 1, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.layoutWidget3)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_3.addWidget(self.label_17, 1, 3, 1, 1)
        self.cPPL1 = QtGui.QComboBox(self.layoutWidget3)
        self.cPPL1.setObjectName(_fromUtf8("cPPL1"))
        self.cPPL1.addItem(_fromUtf8(""))
        self.cPPL1.addItem(_fromUtf8(""))
        self.cPPL1.addItem(_fromUtf8(""))
        self.cPPL1.addItem(_fromUtf8(""))
        self.cPPL1.addItem(_fromUtf8(""))
        self.cPPL1.addItem(_fromUtf8(""))
        self.cPPL1.addItem(_fromUtf8(""))
        self.cPPL1.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cPPL1, 2, 2, 1, 1)
        self.label_18 = QtGui.QLabel(self.layoutWidget3)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_3.addWidget(self.label_18, 2, 0, 3, 1)
        self.cPPF1 = QtGui.QComboBox(self.layoutWidget3)
        self.cPPF1.setObjectName(_fromUtf8("cPPF1"))
        self.cPPF1.addItem(_fromUtf8(""))
        self.cPPF1.addItem(_fromUtf8(""))
        self.cPPF1.addItem(_fromUtf8(""))
        self.cPPF1.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cPPF1, 2, 1, 1, 1)
        self.cPPP1 = QtGui.QComboBox(self.layoutWidget3)
        self.cPPP1.setObjectName(_fromUtf8("cPPP1"))
        self.cPPP1.addItem(_fromUtf8(""))
        self.cPPP1.addItem(_fromUtf8(""))
        self.cPPP1.addItem(_fromUtf8(""))
        self.cPPP1.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cPPP1, 2, 3, 1, 1)
        self.cPPF2 = QtGui.QComboBox(self.layoutWidget3)
        self.cPPF2.setObjectName(_fromUtf8("cPPF2"))
        self.cPPF2.addItem(_fromUtf8(""))
        self.cPPF2.addItem(_fromUtf8(""))
        self.cPPF2.addItem(_fromUtf8(""))
        self.cPPF2.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cPPF2, 3, 1, 1, 1)
        self.cPPF3 = QtGui.QComboBox(self.layoutWidget3)
        self.cPPF3.setObjectName(_fromUtf8("cPPF3"))
        self.cPPF3.addItem(_fromUtf8(""))
        self.cPPF3.addItem(_fromUtf8(""))
        self.cPPF3.addItem(_fromUtf8(""))
        self.cPPF3.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cPPF3, 4, 1, 1, 1)
        self.cPPL2 = QtGui.QComboBox(self.layoutWidget3)
        self.cPPL2.setObjectName(_fromUtf8("cPPL2"))
        self.cPPL2.addItem(_fromUtf8(""))
        self.cPPL2.addItem(_fromUtf8(""))
        self.cPPL2.addItem(_fromUtf8(""))
        self.cPPL2.addItem(_fromUtf8(""))
        self.cPPL2.addItem(_fromUtf8(""))
        self.cPPL2.addItem(_fromUtf8(""))
        self.cPPL2.addItem(_fromUtf8(""))
        self.cPPL2.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cPPL2, 3, 2, 1, 1)
        self.cPPL3 = QtGui.QComboBox(self.layoutWidget3)
        self.cPPL3.setObjectName(_fromUtf8("cPPL3"))
        self.cPPL3.addItem(_fromUtf8(""))
        self.cPPL3.addItem(_fromUtf8(""))
        self.cPPL3.addItem(_fromUtf8(""))
        self.cPPL3.addItem(_fromUtf8(""))
        self.cPPL3.addItem(_fromUtf8(""))
        self.cPPL3.addItem(_fromUtf8(""))
        self.cPPL3.addItem(_fromUtf8(""))
        self.cPPL3.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cPPL3, 4, 2, 1, 1)
        self.cPPP2 = QtGui.QComboBox(self.layoutWidget3)
        self.cPPP2.setObjectName(_fromUtf8("cPPP2"))
        self.cPPP2.addItem(_fromUtf8(""))
        self.cPPP2.addItem(_fromUtf8(""))
        self.cPPP2.addItem(_fromUtf8(""))
        self.cPPP2.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cPPP2, 3, 3, 1, 1)
        self.cPPP3 = QtGui.QComboBox(self.layoutWidget3)
        self.cPPP3.setObjectName(_fromUtf8("cPPP3"))
        self.cPPP3.addItem(_fromUtf8(""))
        self.cPPP3.addItem(_fromUtf8(""))
        self.cPPP3.addItem(_fromUtf8(""))
        self.cPPP3.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cPPP3, 4, 3, 1, 1)
        self.toolBox.addItem(self.tab2, _fromUtf8(""))
        self.tab3 = QtGui.QWidget()
        self.tab3.setGeometry(QtCore.QRect(0, 0, 521, 317))
        self.tab3.setObjectName(_fromUtf8("tab3"))
        self.layoutWidget_2 = QtGui.QWidget(self.tab3)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 0, 491, 142))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget_2)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_28 = QtGui.QLabel(self.layoutWidget_2)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_5.addWidget(self.label_28, 0, 3, 1, 1)
        self.spinHEC = QtGui.QSpinBox(self.layoutWidget_2)
        self.spinHEC.setMinimum(0)
        self.spinHEC.setMaximum(2)
        self.spinHEC.setObjectName(_fromUtf8("spinHEC"))
        self.gridLayout_5.addWidget(self.spinHEC, 1, 2, 1, 1)
        self.label_29 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_5.addWidget(self.label_29, 2, 0, 1, 1)
        self.spinHPHA = QtGui.QSpinBox(self.layoutWidget_2)
        self.spinHPHA.setMinimum(0)
        self.spinHPHA.setMaximum(2)
        self.spinHPHA.setObjectName(_fromUtf8("spinHPHA"))
        self.gridLayout_5.addWidget(self.spinHPHA, 1, 1, 1, 1)
        self.spinHDE = QtGui.QSpinBox(self.layoutWidget_2)
        self.spinHDE.setMinimum(0)
        self.spinHDE.setMaximum(2)
        self.spinHDE.setObjectName(_fromUtf8("spinHDE"))
        self.gridLayout_5.addWidget(self.spinHDE, 3, 1, 1, 1)
        self.label_30 = QtGui.QLabel(self.layoutWidget_2)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_5.addWidget(self.label_30, 0, 1, 1, 1)
        self.label_31 = QtGui.QLabel(self.layoutWidget_2)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_5.addWidget(self.label_31, 0, 2, 1, 1)
        self.spinHRH = QtGui.QSpinBox(self.layoutWidget_2)
        self.spinHRH.setMinimum(0)
        self.spinHRH.setMaximum(2)
        self.spinHRH.setObjectName(_fromUtf8("spinHRH"))
        self.gridLayout_5.addWidget(self.spinHRH, 3, 2, 1, 1)
        self.spinHPP = QtGui.QSpinBox(self.layoutWidget_2)
        self.spinHPP.setMinimum(0)
        self.spinHPP.setMaximum(1)
        self.spinHPP.setObjectName(_fromUtf8("spinHPP"))
        self.gridLayout_5.addWidget(self.spinHPP, 1, 3, 1, 1)
        self.label_32 = QtGui.QLabel(self.layoutWidget_2)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_5.addWidget(self.label_32, 2, 1, 1, 1)
        self.label_33 = QtGui.QLabel(self.layoutWidget_2)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_5.addWidget(self.label_33, 2, 2, 1, 1)
        self.label_34 = QtGui.QLabel(self.layoutWidget_2)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_5.addWidget(self.label_34, 2, 3, 1, 1)
        self.lcdHPT = QtGui.QLCDNumber(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lcdHPT.setFont(font)
        self.lcdHPT.setObjectName(_fromUtf8("lcdHPT"))
        self.gridLayout_5.addWidget(self.lcdHPT, 3, 3, 1, 1)
        self.layoutWidget_3 = QtGui.QWidget(self.tab3)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 150, 491, 111))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.gridLayout_6 = QtGui.QGridLayout(self.layoutWidget_3)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_40 = QtGui.QLabel(self.layoutWidget_3)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_6.addWidget(self.label_40, 2, 2, 1, 1)
        self.label_41 = QtGui.QLabel(self.layoutWidget_3)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_6.addWidget(self.label_41, 2, 3, 1, 1)
        self.label_36 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_6.addWidget(self.label_36, 2, 0, 1, 1)
        self.label_38 = QtGui.QLabel(self.layoutWidget_3)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_6.addWidget(self.label_38, 0, 2, 1, 1)
        self.label_39 = QtGui.QLabel(self.layoutWidget_3)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_6.addWidget(self.label_39, 2, 1, 1, 1)
        self.label_35 = QtGui.QLabel(self.layoutWidget_3)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_6.addWidget(self.label_35, 0, 3, 1, 1)
        self.label_37 = QtGui.QLabel(self.layoutWidget_3)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_6.addWidget(self.label_37, 0, 1, 1, 1)
        self.comboRR = QtGui.QComboBox(self.layoutWidget_3)
        self.comboRR.setObjectName(_fromUtf8("comboRR"))
        self.comboRR.addItem(_fromUtf8(""))
        self.comboRR.addItem(_fromUtf8(""))
        self.comboRR.addItem(_fromUtf8(""))
        self.comboRR.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.comboRR, 1, 1, 1, 1)
        self.comboRA = QtGui.QComboBox(self.layoutWidget_3)
        self.comboRA.setObjectName(_fromUtf8("comboRA"))
        self.comboRA.addItem(_fromUtf8(""))
        self.comboRA.addItem(_fromUtf8(""))
        self.comboRA.addItem(_fromUtf8(""))
        self.comboRA.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.comboRA, 1, 2, 1, 1)
        self.comboRS = QtGui.QComboBox(self.layoutWidget_3)
        self.comboRS.setObjectName(_fromUtf8("comboRS"))
        self.comboRS.addItem(_fromUtf8(""))
        self.comboRS.addItem(_fromUtf8(""))
        self.comboRS.addItem(_fromUtf8(""))
        self.comboRS.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.comboRS, 1, 3, 1, 1)
        self.comboRAst = QtGui.QComboBox(self.layoutWidget_3)
        self.comboRAst.setObjectName(_fromUtf8("comboRAst"))
        self.comboRAst.addItem(_fromUtf8(""))
        self.comboRAst.addItem(_fromUtf8(""))
        self.comboRAst.addItem(_fromUtf8(""))
        self.comboRAst.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.comboRAst, 3, 1, 1, 1)
        self.comboRT = QtGui.QComboBox(self.layoutWidget_3)
        self.comboRT.setObjectName(_fromUtf8("comboRT"))
        self.comboRT.addItem(_fromUtf8(""))
        self.comboRT.addItem(_fromUtf8(""))
        self.comboRT.addItem(_fromUtf8(""))
        self.comboRT.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.comboRT, 3, 2, 1, 1)
        self.comboRI = QtGui.QComboBox(self.layoutWidget_3)
        self.comboRI.setObjectName(_fromUtf8("comboRI"))
        self.comboRI.addItem(_fromUtf8(""))
        self.comboRI.addItem(_fromUtf8(""))
        self.comboRI.addItem(_fromUtf8(""))
        self.comboRI.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.comboRI, 3, 3, 1, 1)
        self.layoutWidget4 = QtGui.QWidget(self.tab3)
        self.layoutWidget4.setGeometry(QtCore.QRect(20, 270, 491, 29))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_42 = QtGui.QLabel(self.layoutWidget4)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.horizontalLayout.addWidget(self.label_42)
        self.spinTMA = QtGui.QSpinBox(self.layoutWidget4)
        self.spinTMA.setObjectName(_fromUtf8("spinTMA"))
        self.horizontalLayout.addWidget(self.spinTMA)
        spacerItem = QtGui.QSpacerItem(168, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.line_2 = QtGui.QFrame(self.tab3)
        self.line_2.setGeometry(QtCore.QRect(10, 135, 491, 21))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.toolBox.addItem(self.tab3, _fromUtf8(""))
        self.tab4 = QtGui.QWidget()
        self.tab4.setGeometry(QtCore.QRect(0, 0, 521, 317))
        self.tab4.setObjectName(_fromUtf8("tab4"))
        self.layoutWidget_4 = QtGui.QWidget(self.tab4)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 0, 481, 161))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.gridLayout_7 = QtGui.QGridLayout(self.layoutWidget_4)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.editSLO = QtGui.QLineEdit(self.layoutWidget_4)
        self.editSLO.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.editSLO.setObjectName(_fromUtf8("editSLO"))
        self.gridLayout_7.addWidget(self.editSLO, 1, 3, 1, 1)
        self.label_52 = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_52.setFont(font)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.gridLayout_7.addWidget(self.label_52, 1, 4, 1, 1)
        self.editNHR = QtGui.QLineEdit(self.layoutWidget_4)
        self.editNHR.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.editNHR.setObjectName(_fromUtf8("editNHR"))
        self.gridLayout_7.addWidget(self.editNHR, 3, 1, 1, 1)
        self.label_49 = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_49.setFont(font)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.gridLayout_7.addWidget(self.label_49, 3, 2, 1, 1)
        self.label_47 = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.gridLayout_7.addWidget(self.label_47, 2, 1, 1, 1)
        self.label_48 = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.gridLayout_7.addWidget(self.label_48, 2, 2, 1, 1)
        self.label_50 = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.gridLayout_7.addWidget(self.label_50, 0, 4, 1, 1)
        self.label_46 = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_7.addWidget(self.label_46, 0, 2, 1, 1)
        self.label_45 = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_7.addWidget(self.label_45, 0, 1, 1, 1)
        self.label_51 = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_51.setFont(font)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout_7.addWidget(self.label_51, 1, 2, 1, 1)
        self.editJLO = QtGui.QLineEdit(self.layoutWidget_4)
        self.editJLO.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.editJLO.setObjectName(_fromUtf8("editJLO"))
        self.gridLayout_7.addWidget(self.editJLO, 1, 1, 1, 1)
        self.label_43 = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_7.addWidget(self.label_43, 0, 3, 1, 1)
        self.label_44 = QtGui.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_7.addWidget(self.label_44, 0, 0, 4, 1)
        self.layoutWidget_5 = QtGui.QWidget(self.tab4)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 160, 481, 151))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.gridLayout_8 = QtGui.QGridLayout(self.layoutWidget_5)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.editFF = QtGui.QLineEdit(self.layoutWidget_5)
        self.editFF.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.editFF.setObjectName(_fromUtf8("editFF"))
        self.gridLayout_8.addWidget(self.editFF, 2, 1, 1, 1)
        self.editRFF = QtGui.QLineEdit(self.layoutWidget_5)
        self.editRFF.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.editRFF.setObjectName(_fromUtf8("editRFF"))
        self.gridLayout_8.addWidget(self.editRFF, 2, 2, 1, 1)
        self.label_56 = QtGui.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.gridLayout_8.addWidget(self.label_56, 3, 2, 1, 1)
        self.editT = QtGui.QLineEdit(self.layoutWidget_5)
        self.editT.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.editT.setObjectName(_fromUtf8("editT"))
        self.gridLayout_8.addWidget(self.editT, 2, 4, 1, 1)
        self.label_59 = QtGui.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_59.setFont(font)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.gridLayout_8.addWidget(self.label_59, 1, 1, 1, 1)
        self.label_55 = QtGui.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.gridLayout_8.addWidget(self.label_55, 3, 1, 1, 1)
        self.label_58 = QtGui.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_58.setFont(font)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.gridLayout_8.addWidget(self.label_58, 1, 2, 1, 1)
        self.label_57 = QtGui.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_57.setFont(font)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.gridLayout_8.addWidget(self.label_57, 1, 4, 1, 1)
        self.label_63 = QtGui.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_63.setFont(font)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.gridLayout_8.addWidget(self.label_63, 3, 3, 1, 1)
        self.editRET = QtGui.QLineEdit(self.layoutWidget_5)
        self.editRET.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.editRET.setObjectName(_fromUtf8("editRET"))
        self.gridLayout_8.addWidget(self.editRET, 2, 3, 1, 1)
        self.comboTC = QtGui.QComboBox(self.layoutWidget_5)
        self.comboTC.setObjectName(_fromUtf8("comboTC"))
        self.comboTC.addItem(_fromUtf8(""))
        self.comboTC.addItem(_fromUtf8(""))
        self.comboTC.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.comboTC, 4, 1, 1, 1)
        self.label_62 = QtGui.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_62.setFont(font)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.gridLayout_8.addWidget(self.label_62, 1, 3, 1, 1)
        self.comboCVM = QtGui.QComboBox(self.layoutWidget_5)
        self.comboCVM.setObjectName(_fromUtf8("comboCVM"))
        self.comboCVM.addItem(_fromUtf8(""))
        self.comboCVM.addItem(_fromUtf8(""))
        self.comboCVM.addItem(_fromUtf8(""))
        self.comboCVM.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.comboCVM, 4, 3, 1, 1)
        self.comboCVH = QtGui.QComboBox(self.layoutWidget_5)
        self.comboCVH.setObjectName(_fromUtf8("comboCVH"))
        self.comboCVH.addItem(_fromUtf8(""))
        self.comboCVH.addItem(_fromUtf8(""))
        self.comboCVH.addItem(_fromUtf8(""))
        self.comboCVH.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.comboCVH, 4, 2, 1, 1)
        self.label_60 = QtGui.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_60.setFont(font)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.gridLayout_8.addWidget(self.label_60, 1, 0, 4, 1)
        self.line_5 = QtGui.QFrame(self.layoutWidget_5)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout_8.addWidget(self.line_5, 0, 0, 1, 5)
        self.toolBox.addItem(self.tab4, _fromUtf8(""))
        self.labelNombre = QtGui.QLabel(self.centralWidget)
        self.labelNombre.setGeometry(QtCore.QRect(10, 0, 301, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelNombre.setFont(font)
        self.labelNombre.setObjectName(_fromUtf8("labelNombre"))
        self.labelRun = QtGui.QLabel(self.centralWidget)
        self.labelRun.setGeometry(QtCore.QRect(320, 0, 201, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelRun.setFont(font)
        self.labelRun.setObjectName(_fromUtf8("labelRun"))
        EvaluacionVocal.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(EvaluacionVocal)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 535, 25))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        EvaluacionVocal.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(EvaluacionVocal)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        EvaluacionVocal.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(EvaluacionVocal)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        EvaluacionVocal.setStatusBar(self.statusBar)

        self.retranslateUi(EvaluacionVocal)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(EvaluacionVocal)

    def retranslateUi(self, EvaluacionVocal):
        EvaluacionVocal.setWindowTitle(_translate("EvaluacionVocal", "EVALUACION VOCAL", None))
        self.pushButton.setText(_translate("EvaluacionVocal", "Guardar", None))
        self.label_2.setText(_translate("EvaluacionVocal", "Funcional", None))
        self.labelFIsica.setText(_translate("EvaluacionVocal", "Física", None))
        self.label_4.setText(_translate("EvaluacionVocal", "Emocional", None))
        self.label_3.setText(_translate("EvaluacionVocal", "TOTAL", None))
        self.label.setText(_translate("EvaluacionVocal", "Puntaje VHI", None))
        self.comboTRR.setItemText(0, _translate("EvaluacionVocal", "Ninguna", None))
        self.comboTRR.setItemText(1, _translate("EvaluacionVocal", "Costal alto", None))
        self.comboTRR.setItemText(2, _translate("EvaluacionVocal", "Abdominal", None))
        self.comboTRR.setItemText(3, _translate("EvaluacionVocal", "Mixto", None))
        self.comboTRR.setItemText(4, _translate("EvaluacionVocal", "Costo diafragmático", None))
        self.label_7.setText(_translate("EvaluacionVocal", "Modo respiratrio\n"
"en reposo", None))
        self.label_14.setText(_translate("EvaluacionVocal", "Apoyo\n"
"respiratorio", None))
        self.comboMRR.setItemText(0, _translate("EvaluacionVocal", "Ninguna", None))
        self.comboMRR.setItemText(1, _translate("EvaluacionVocal", "Predominio nasal", None))
        self.comboMRR.setItemText(2, _translate("EvaluacionVocal", "Predomonio bucal", None))
        self.label_10.setText(_translate("EvaluacionVocal", "Número de inspiraciones\n"
"durante conteo", None))
        self.comboCFR.setItemText(0, _translate("EvaluacionVocal", "Ninguna", None))
        self.comboCFR.setItemText(1, _translate("EvaluacionVocal", "Adecuada", None))
        self.comboCFR.setItemText(2, _translate("EvaluacionVocal", "Regular", None))
        self.comboCFR.setItemText(3, _translate("EvaluacionVocal", "Pobre - alterada", None))
        self.comboAR.setItemText(0, _translate("EvaluacionVocal", "Ninguno", None))
        self.comboAR.setItemText(1, _translate("EvaluacionVocal", "Bueno", None))
        self.comboAR.setItemText(2, _translate("EvaluacionVocal", "Regular", None))
        self.comboAR.setItemText(3, _translate("EvaluacionVocal", "Malo", None))
        self.label_5.setText(_translate("EvaluacionVocal", "Tipo respiratrio\n"
"en reposo", None))
        self.label_9.setText(_translate("EvaluacionVocal", "Coordinación\n"
"fono-respiratoria", None))
        self.label_11.setText(_translate("EvaluacionVocal", "Tiempo máximo\n"
"de fonación", None))
        self.label_12.setText(_translate("EvaluacionVocal", "Índice s/a", None))
        self.label_13.setText(_translate("EvaluacionVocal", "Tiempo máximo\n"
"de espiración", None))
        self.comboTRF.setItemText(0, _translate("EvaluacionVocal", "Ninguna", None))
        self.comboTRF.setItemText(1, _translate("EvaluacionVocal", "Costal alto", None))
        self.comboTRF.setItemText(2, _translate("EvaluacionVocal", "Abdominal", None))
        self.comboTRF.setItemText(3, _translate("EvaluacionVocal", "Mixto", None))
        self.comboTRF.setItemText(4, _translate("EvaluacionVocal", "Costo diafragmático", None))
        self.comboBox_2.setItemText(0, _translate("EvaluacionVocal", "Ninguna", None))
        self.comboBox_2.setItemText(1, _translate("EvaluacionVocal", "Predominio nasal", None))
        self.comboBox_2.setItemText(2, _translate("EvaluacionVocal", "Predominio bucal", None))
        self.label_6.setText(_translate("EvaluacionVocal", "Tipo respiratrio\n"
"en fonación", None))
        self.label_8.setText(_translate("EvaluacionVocal", "Modo respiratrio\n"
"en fonación", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tab1), _translate("EvaluacionVocal", "Principal", None))
        self.label_23.setText(_translate("EvaluacionVocal", "Suprahioidea", None))
        self.label_21.setText(_translate("EvaluacionVocal", "General", None))
        self.label_22.setText(_translate("EvaluacionVocal", "Infrahioidea", None))
        self.label_20.setText(_translate("EvaluacionVocal", "Cervical", None))
        self.label_25.setText(_translate("EvaluacionVocal", "Cintura\n"
"escapular", None))
        self.label_26.setText(_translate("EvaluacionVocal", "Altura\n"
"laringea", None))
        self.label_24.setText(_translate("EvaluacionVocal", "Tonicidad", None))
        self.cTonG.setItemText(0, _translate("EvaluacionVocal", "Ninguna", None))
        self.cTonG.setItemText(1, _translate("EvaluacionVocal", "Eutonía", None))
        self.cTonG.setItemText(2, _translate("EvaluacionVocal", "Hipotonía", None))
        self.cTonG.setItemText(3, _translate("EvaluacionVocal", "Hipertornía", None))
        self.cTonI.setItemText(0, _translate("EvaluacionVocal", "Ninguna", None))
        self.cTonI.setItemText(1, _translate("EvaluacionVocal", "Eutonía", None))
        self.cTonI.setItemText(2, _translate("EvaluacionVocal", "Hipotonía", None))
        self.cTonI.setItemText(3, _translate("EvaluacionVocal", "Hipertornía", None))
        self.cTonS.setItemText(0, _translate("EvaluacionVocal", "Ninguna", None))
        self.cTonS.setItemText(1, _translate("EvaluacionVocal", "Eutonía", None))
        self.cTonS.setItemText(2, _translate("EvaluacionVocal", "Hipotonía", None))
        self.cTonS.setItemText(3, _translate("EvaluacionVocal", "Hipertornía", None))
        self.cTonC.setItemText(0, _translate("EvaluacionVocal", "Ninguna", None))
        self.cTonC.setItemText(1, _translate("EvaluacionVocal", "Eutonía", None))
        self.cTonC.setItemText(2, _translate("EvaluacionVocal", "Hipotonía", None))
        self.cTonC.setItemText(3, _translate("EvaluacionVocal", "Hipertornía", None))
        self.cTonCE.setItemText(0, _translate("EvaluacionVocal", "Ninguna", None))
        self.cTonCE.setItemText(1, _translate("EvaluacionVocal", "Eutonía", None))
        self.cTonCE.setItemText(2, _translate("EvaluacionVocal", "Hipotonía", None))
        self.cTonCE.setItemText(3, _translate("EvaluacionVocal", "Hipertornía", None))
        self.cTonAL.setItemText(0, _translate("EvaluacionVocal", "Ninguna", None))
        self.cTonAL.setItemText(1, _translate("EvaluacionVocal", "Normal", None))
        self.cTonAL.setItemText(2, _translate("EvaluacionVocal", "Ascendida", None))
        self.cTonAL.setItemText(3, _translate("EvaluacionVocal", "Descendida", None))
        self.cTonAL.setItemText(4, _translate("EvaluacionVocal", "Anteriorizada", None))
        self.cTonAL.setItemText(5, _translate("EvaluacionVocal", "Posteriorizada", None))
        self.cTonAL.setItemText(6, _translate("EvaluacionVocal", "Sin cracea", None))
        self.cTonAL.setItemText(7, _translate("EvaluacionVocal", "Desplacamiento lateral hacia derecha", None))
        self.cTonAL.setItemText(8, _translate("EvaluacionVocal", "Desplacamiento lateral hacia izquierda", None))
        self.label_27.setText(_translate("EvaluacionVocal", "Observaciones", None))
        self.label_19.setText(_translate("EvaluacionVocal", "Planos", None))
        self.label_15.setText(_translate("EvaluacionVocal", "Frontal", None))
        self.label_16.setText(_translate("EvaluacionVocal", "Lateral", None))
        self.label_17.setText(_translate("EvaluacionVocal", "Posterior", None))
        self.cPPL1.setItemText(0, _translate("EvaluacionVocal", "Ninguna", None))
        self.cPPL1.setItemText(1, _translate("EvaluacionVocal", "Adecuado", None))
        self.cPPL1.setItemText(2, _translate("EvaluacionVocal", "Cabeza adelantada", None))
        self.cPPL1.setItemText(3, _translate("EvaluacionVocal", "Hipercifosis", None))
        self.cPPL1.setItemText(4, _translate("EvaluacionVocal", "Hiperlordosis", None))
        self.cPPL1.setItemText(5, _translate("EvaluacionVocal", "Rectificación cervical", None))
        self.cPPL1.setItemText(6, _translate("EvaluacionVocal", "Rectificación dorsal", None))
        self.cPPL1.setItemText(7, _translate("EvaluacionVocal", "Rectificación lumbar", None))
        self.label_18.setText(_translate("EvaluacionVocal", "Postura", None))
        self.cPPF1.setItemText(0, _translate("EvaluacionVocal", "Ninguno", None))
        self.cPPF1.setItemText(1, _translate("EvaluacionVocal", "Adecuado", None))
        self.cPPF1.setItemText(2, _translate("EvaluacionVocal", "Hacia derecha", None))
        self.cPPF1.setItemText(3, _translate("EvaluacionVocal", "Hacia izquierda", None))
        self.cPPP1.setItemText(0, _translate("EvaluacionVocal", "Ninguno", None))
        self.cPPP1.setItemText(1, _translate("EvaluacionVocal", "Adecuado", None))
        self.cPPP1.setItemText(2, _translate("EvaluacionVocal", "Hacia derecha", None))
        self.cPPP1.setItemText(3, _translate("EvaluacionVocal", "Hacia izquierda", None))
        self.cPPF2.setItemText(0, _translate("EvaluacionVocal", "Ninguno", None))
        self.cPPF2.setItemText(1, _translate("EvaluacionVocal", "Adecuado", None))
        self.cPPF2.setItemText(2, _translate("EvaluacionVocal", "Hacia derecha", None))
        self.cPPF2.setItemText(3, _translate("EvaluacionVocal", "Hacia izquierda", None))
        self.cPPF3.setItemText(0, _translate("EvaluacionVocal", "Ninguno", None))
        self.cPPF3.setItemText(1, _translate("EvaluacionVocal", "Adecuado", None))
        self.cPPF3.setItemText(2, _translate("EvaluacionVocal", "Hacia derecha", None))
        self.cPPF3.setItemText(3, _translate("EvaluacionVocal", "Hacia izquierda", None))
        self.cPPL2.setItemText(0, _translate("EvaluacionVocal", "Ninguna", None))
        self.cPPL2.setItemText(1, _translate("EvaluacionVocal", "Adecuado", None))
        self.cPPL2.setItemText(2, _translate("EvaluacionVocal", "Cabeza adelantada", None))
        self.cPPL2.setItemText(3, _translate("EvaluacionVocal", "Hipercifosis", None))
        self.cPPL2.setItemText(4, _translate("EvaluacionVocal", "Hiperlordosis", None))
        self.cPPL2.setItemText(5, _translate("EvaluacionVocal", "Rectificación cervical", None))
        self.cPPL2.setItemText(6, _translate("EvaluacionVocal", "Rectificación dorsal", None))
        self.cPPL2.setItemText(7, _translate("EvaluacionVocal", "Rectificación lumbar", None))
        self.cPPL3.setItemText(0, _translate("EvaluacionVocal", "Ninguna", None))
        self.cPPL3.setItemText(1, _translate("EvaluacionVocal", "Adecuado", None))
        self.cPPL3.setItemText(2, _translate("EvaluacionVocal", "Cabeza adelantada", None))
        self.cPPL3.setItemText(3, _translate("EvaluacionVocal", "Hipercifosis", None))
        self.cPPL3.setItemText(4, _translate("EvaluacionVocal", "Hiperlordosis", None))
        self.cPPL3.setItemText(5, _translate("EvaluacionVocal", "Rectificación cervical", None))
        self.cPPL3.setItemText(6, _translate("EvaluacionVocal", "Rectificación dorsal", None))
        self.cPPL3.setItemText(7, _translate("EvaluacionVocal", "Rectificación lumbar", None))
        self.cPPP2.setItemText(0, _translate("EvaluacionVocal", "Ninguno", None))
        self.cPPP2.setItemText(1, _translate("EvaluacionVocal", "Adecuado", None))
        self.cPPP2.setItemText(2, _translate("EvaluacionVocal", "Hacia derecha", None))
        self.cPPP2.setItemText(3, _translate("EvaluacionVocal", "Hacia izquierda", None))
        self.cPPP3.setItemText(0, _translate("EvaluacionVocal", "Ninguno", None))
        self.cPPP3.setItemText(1, _translate("EvaluacionVocal", "Adecuado", None))
        self.cPPP3.setItemText(2, _translate("EvaluacionVocal", "Hacia derecha", None))
        self.cPPP3.setItemText(3, _translate("EvaluacionVocal", "Hacia izquierda", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tab2), _translate("EvaluacionVocal", "Postura y tonicidad", None))
        self.label_28.setText(_translate("EvaluacionVocal", "Punta\n"
"de pies", None))
        self.label_29.setText(_translate("EvaluacionVocal", "Hiperlaxitud", None))
        self.label_30.setText(_translate("EvaluacionVocal", "Pulgar hacia\n"
"antebrazo", None))
        self.label_31.setText(_translate("EvaluacionVocal", "Extensión\n"
"del codo", None))
        self.label_32.setText(_translate("EvaluacionVocal", "Dedos en\n"
"extensión", None))
        self.label_33.setText(_translate("EvaluacionVocal", "Rodillas en\n"
"hiperextensión", None))
        self.label_34.setText(_translate("EvaluacionVocal", "Puntaje Total", None))
        self.label_40.setText(_translate("EvaluacionVocal", "Tensión", None))
        self.label_41.setText(_translate("EvaluacionVocal", "Inestabilidad", None))
        self.label_36.setText(_translate("EvaluacionVocal", "RASATI", None))
        self.label_38.setText(_translate("EvaluacionVocal", "Aspereza", None))
        self.label_39.setText(_translate("EvaluacionVocal", "Astenia", None))
        self.label_35.setText(_translate("EvaluacionVocal", "Soplicidad", None))
        self.label_37.setText(_translate("EvaluacionVocal", "Ronquera", None))
        self.comboRR.setItemText(0, _translate("EvaluacionVocal", "Normal", None))
        self.comboRR.setItemText(1, _translate("EvaluacionVocal", "Leve", None))
        self.comboRR.setItemText(2, _translate("EvaluacionVocal", "Moderado", None))
        self.comboRR.setItemText(3, _translate("EvaluacionVocal", "Intenso", None))
        self.comboRA.setItemText(0, _translate("EvaluacionVocal", "Normal", None))
        self.comboRA.setItemText(1, _translate("EvaluacionVocal", "Leve", None))
        self.comboRA.setItemText(2, _translate("EvaluacionVocal", "Moderado", None))
        self.comboRA.setItemText(3, _translate("EvaluacionVocal", "Intenso", None))
        self.comboRS.setItemText(0, _translate("EvaluacionVocal", "Normal", None))
        self.comboRS.setItemText(1, _translate("EvaluacionVocal", "Leve", None))
        self.comboRS.setItemText(2, _translate("EvaluacionVocal", "Moderado", None))
        self.comboRS.setItemText(3, _translate("EvaluacionVocal", "Intenso", None))
        self.comboRAst.setItemText(0, _translate("EvaluacionVocal", "Normal", None))
        self.comboRAst.setItemText(1, _translate("EvaluacionVocal", "Leve", None))
        self.comboRAst.setItemText(2, _translate("EvaluacionVocal", "Moderado", None))
        self.comboRAst.setItemText(3, _translate("EvaluacionVocal", "Intenso", None))
        self.comboRT.setItemText(0, _translate("EvaluacionVocal", "Normal", None))
        self.comboRT.setItemText(1, _translate("EvaluacionVocal", "Leve", None))
        self.comboRT.setItemText(2, _translate("EvaluacionVocal", "Moderado", None))
        self.comboRT.setItemText(3, _translate("EvaluacionVocal", "Intenso", None))
        self.comboRI.setItemText(0, _translate("EvaluacionVocal", "Normal", None))
        self.comboRI.setItemText(1, _translate("EvaluacionVocal", "Leve", None))
        self.comboRI.setItemText(2, _translate("EvaluacionVocal", "Moderado", None))
        self.comboRI.setItemText(3, _translate("EvaluacionVocal", "Intenso", None))
        self.label_42.setText(_translate("EvaluacionVocal", "Tono medio hablado", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tab3), _translate("EvaluacionVocal", "Hiperlaxitud, RASATI y tono media hablado", None))
        self.label_52.setText(_translate("EvaluacionVocal", "< 3,810 %", None))
        self.label_49.setText(_translate("EvaluacionVocal", "> 20 dB", None))
        self.label_47.setText(_translate("EvaluacionVocal", "NHR\n"
"obtenido", None))
        self.label_48.setText(_translate("EvaluacionVocal", "Rango NHR\n"
"esperado\n"
"(Praat)", None))
        self.label_50.setText(_translate("EvaluacionVocal", "Rango\n"
"Shimmer local\n"
"esperado (Praat)", None))
        self.label_46.setText(_translate("EvaluacionVocal", "Rango Jitter\n"
"local esperado\n"
"(Praat)", None))
        self.label_45.setText(_translate("EvaluacionVocal", "Jitter local\n"
"obtenido", None))
        self.label_51.setText(_translate("EvaluacionVocal", "< 1,040 %", None))
        self.label_43.setText(_translate("EvaluacionVocal", "Shimmer local\n"
"obtenido", None))
        self.label_44.setText(_translate("EvaluacionVocal", "Parámetros\n"
"acústicos", None))
        self.label_56.setText(_translate("EvaluacionVocal", "Clasificación vocal\n"
"hombre", None))
        self.label_59.setText(_translate("EvaluacionVocal", "Frecuencia\n"
"fundamenta", None))
        self.label_55.setText(_translate("EvaluacionVocal", "Tipo Cantante", None))
        self.label_58.setText(_translate("EvaluacionVocal", "Rango\n"
"frecuencial", None))
        self.label_57.setText(_translate("EvaluacionVocal", "Tesitura", None))
        self.label_63.setText(_translate("EvaluacionVocal", "Clasificación vocal\n"
"mujer", None))
        self.comboTC.setItemText(0, _translate("EvaluacionVocal", "Ninguno", None))
        self.comboTC.setItemText(1, _translate("EvaluacionVocal", "Cantante popular", None))
        self.comboTC.setItemText(2, _translate("EvaluacionVocal", "Cantante lírico", None))
        self.label_62.setText(_translate("EvaluacionVocal", "Rango tonal\n"
"extensión tonal", None))
        self.comboCVM.setItemText(0, _translate("EvaluacionVocal", "Ninguno", None))
        self.comboCVM.setItemText(1, _translate("EvaluacionVocal", "Soprano", None))
        self.comboCVM.setItemText(2, _translate("EvaluacionVocal", "Mezzosoprano", None))
        self.comboCVM.setItemText(3, _translate("EvaluacionVocal", "Contralto", None))
        self.comboCVH.setItemText(0, _translate("EvaluacionVocal", "Ninguno", None))
        self.comboCVH.setItemText(1, _translate("EvaluacionVocal", "Tenor", None))
        self.comboCVH.setItemText(2, _translate("EvaluacionVocal", "Barítono", None))
        self.comboCVH.setItemText(3, _translate("EvaluacionVocal", "Bajo", None))
        self.label_60.setText(_translate("EvaluacionVocal", "Voz\n"
"cantada", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.tab4), _translate("EvaluacionVocal", "Parámetros acústicos y voz cantada", None))
        self.labelNombre.setText(_translate("EvaluacionVocal", "TextLabel", None))
        self.labelRun.setText(_translate("EvaluacionVocal", "TextLabel", None))

