# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sintomatologianuevo.ui'
#
# Created: Tue Feb 10 21:44:43 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SintomaConducta(object):
    def setupUi(self, SintomaConducta):
        SintomaConducta.setObjectName(_fromUtf8("SintomaConducta"))
        SintomaConducta.resize(671, 511)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../img/aav50.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SintomaConducta.setWindowIcon(icon)
        self.layoutWidget = QtGui.QWidget(SintomaConducta)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 140, 651, 71))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.os1 = QtGui.QComboBox(self.layoutWidget)
        self.os1.setObjectName(_fromUtf8("os1"))
        self.os1.addItem(_fromUtf8(""))
        self.os1.addItem(_fromUtf8(""))
        self.os1.addItem(_fromUtf8(""))
        self.os1.addItem(_fromUtf8(""))
        self.os1.addItem(_fromUtf8(""))
        self.os1.addItem(_fromUtf8(""))
        self.os1.addItem(_fromUtf8(""))
        self.os1.addItem(_fromUtf8(""))
        self.os1.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.os1, 0, 1, 1, 1)
        self.os2 = QtGui.QComboBox(self.layoutWidget)
        self.os2.setObjectName(_fromUtf8("os2"))
        self.os2.addItem(_fromUtf8(""))
        self.os2.addItem(_fromUtf8(""))
        self.os2.addItem(_fromUtf8(""))
        self.os2.addItem(_fromUtf8(""))
        self.os2.addItem(_fromUtf8(""))
        self.os2.addItem(_fromUtf8(""))
        self.os2.addItem(_fromUtf8(""))
        self.os2.addItem(_fromUtf8(""))
        self.os2.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.os2, 0, 2, 1, 1)
        self.os3 = QtGui.QComboBox(self.layoutWidget)
        self.os3.setObjectName(_fromUtf8("os3"))
        self.os3.addItem(_fromUtf8(""))
        self.os3.addItem(_fromUtf8(""))
        self.os3.addItem(_fromUtf8(""))
        self.os3.addItem(_fromUtf8(""))
        self.os3.addItem(_fromUtf8(""))
        self.os3.addItem(_fromUtf8(""))
        self.os3.addItem(_fromUtf8(""))
        self.os3.addItem(_fromUtf8(""))
        self.os3.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.os3, 0, 3, 1, 1)
        self.os4 = QtGui.QComboBox(self.layoutWidget)
        self.os4.setObjectName(_fromUtf8("os4"))
        self.os4.addItem(_fromUtf8(""))
        self.os4.addItem(_fromUtf8(""))
        self.os4.addItem(_fromUtf8(""))
        self.os4.addItem(_fromUtf8(""))
        self.os4.addItem(_fromUtf8(""))
        self.os4.addItem(_fromUtf8(""))
        self.os4.addItem(_fromUtf8(""))
        self.os4.addItem(_fromUtf8(""))
        self.os4.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.os4, 0, 4, 1, 1)
        self.dos2 = QtGui.QLineEdit(self.layoutWidget)
        self.dos2.setObjectName(_fromUtf8("dos2"))
        self.gridLayout_2.addWidget(self.dos2, 1, 2, 1, 1)
        self.dos1 = QtGui.QLineEdit(self.layoutWidget)
        self.dos1.setObjectName(_fromUtf8("dos1"))
        self.gridLayout_2.addWidget(self.dos1, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.dos3 = QtGui.QLineEdit(self.layoutWidget)
        self.dos3.setObjectName(_fromUtf8("dos3"))
        self.gridLayout_2.addWidget(self.dos3, 1, 3, 1, 1)
        self.dos4 = QtGui.QLineEdit(self.layoutWidget)
        self.dos4.setObjectName(_fromUtf8("dos4"))
        self.gridLayout_2.addWidget(self.dos4, 1, 4, 1, 1)
        self.line_2 = QtGui.QFrame(self.layoutWidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_2.addWidget(self.line_2, 2, 0, 1, 5)
        self.layoutWidget_2 = QtGui.QWidget(SintomaConducta)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 300, 651, 80))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_6 = QtGui.QLabel(self.layoutWidget_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.textMQC = QtGui.QPlainTextEdit(self.layoutWidget_2)
        self.textMQC.setObjectName(_fromUtf8("textMQC"))
        self.horizontalLayout_2.addWidget(self.textMQC)
        self.layoutWidget_3 = QtGui.QWidget(SintomaConducta)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 390, 651, 78))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget_3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_7 = QtGui.QLabel(self.layoutWidget_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.cav1 = QtGui.QComboBox(self.layoutWidget_3)
        self.cav1.setObjectName(_fromUtf8("cav1"))
        self.cav1.addItem(_fromUtf8(""))
        self.cav1.addItem(_fromUtf8(""))
        self.cav1.addItem(_fromUtf8(""))
        self.cav1.addItem(_fromUtf8(""))
        self.cav1.addItem(_fromUtf8(""))
        self.cav1.addItem(_fromUtf8(""))
        self.cav1.addItem(_fromUtf8(""))
        self.cav1.addItem(_fromUtf8(""))
        self.cav1.addItem(_fromUtf8(""))
        self.cav1.addItem(_fromUtf8(""))
        self.cav1.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cav1, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 1)
        self.dcav1 = QtGui.QLineEdit(self.layoutWidget_3)
        self.dcav1.setObjectName(_fromUtf8("dcav1"))
        self.gridLayout_3.addWidget(self.dcav1, 2, 1, 1, 1)
        self.dcav2 = QtGui.QLineEdit(self.layoutWidget_3)
        self.dcav2.setObjectName(_fromUtf8("dcav2"))
        self.gridLayout_3.addWidget(self.dcav2, 2, 2, 1, 1)
        self.cav2 = QtGui.QComboBox(self.layoutWidget_3)
        self.cav2.setObjectName(_fromUtf8("cav2"))
        self.cav2.addItem(_fromUtf8(""))
        self.cav2.addItem(_fromUtf8(""))
        self.cav2.addItem(_fromUtf8(""))
        self.cav2.addItem(_fromUtf8(""))
        self.cav2.addItem(_fromUtf8(""))
        self.cav2.addItem(_fromUtf8(""))
        self.cav2.addItem(_fromUtf8(""))
        self.cav2.addItem(_fromUtf8(""))
        self.cav2.addItem(_fromUtf8(""))
        self.cav2.addItem(_fromUtf8(""))
        self.cav2.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cav2, 1, 2, 1, 1)
        self.dcav4 = QtGui.QLineEdit(self.layoutWidget_3)
        self.dcav4.setObjectName(_fromUtf8("dcav4"))
        self.gridLayout_3.addWidget(self.dcav4, 2, 4, 1, 1)
        self.dcav3 = QtGui.QLineEdit(self.layoutWidget_3)
        self.dcav3.setObjectName(_fromUtf8("dcav3"))
        self.gridLayout_3.addWidget(self.dcav3, 2, 3, 1, 1)
        self.cav3 = QtGui.QComboBox(self.layoutWidget_3)
        self.cav3.setObjectName(_fromUtf8("cav3"))
        self.cav3.addItem(_fromUtf8(""))
        self.cav3.addItem(_fromUtf8(""))
        self.cav3.addItem(_fromUtf8(""))
        self.cav3.addItem(_fromUtf8(""))
        self.cav3.addItem(_fromUtf8(""))
        self.cav3.addItem(_fromUtf8(""))
        self.cav3.addItem(_fromUtf8(""))
        self.cav3.addItem(_fromUtf8(""))
        self.cav3.addItem(_fromUtf8(""))
        self.cav3.addItem(_fromUtf8(""))
        self.cav3.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cav3, 1, 3, 1, 1)
        self.cav4 = QtGui.QComboBox(self.layoutWidget_3)
        self.cav4.setObjectName(_fromUtf8("cav4"))
        self.cav4.addItem(_fromUtf8(""))
        self.cav4.addItem(_fromUtf8(""))
        self.cav4.addItem(_fromUtf8(""))
        self.cav4.addItem(_fromUtf8(""))
        self.cav4.addItem(_fromUtf8(""))
        self.cav4.addItem(_fromUtf8(""))
        self.cav4.addItem(_fromUtf8(""))
        self.cav4.addItem(_fromUtf8(""))
        self.cav4.addItem(_fromUtf8(""))
        self.cav4.addItem(_fromUtf8(""))
        self.cav4.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cav4, 1, 4, 1, 1)
        self.line_3 = QtGui.QFrame(self.layoutWidget_3)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_3.addWidget(self.line_3, 0, 0, 1, 5)
        self.label_9 = QtGui.QLabel(SintomaConducta)
        self.label_9.setGeometry(QtCore.QRect(10, 480, 131, 17))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(SintomaConducta)
        self.label_10.setGeometry(QtCore.QRect(20, 20, 67, 17))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.bguardar = QtGui.QPushButton(SintomaConducta)
        self.bguardar.setGeometry(QtCore.QRect(550, 470, 99, 27))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../img/edit16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bguardar.setIcon(icon1)
        self.bguardar.setObjectName(_fromUtf8("bguardar"))
        self.nombrep = QtGui.QLabel(SintomaConducta)
        self.nombrep.setGeometry(QtCore.QRect(90, 10, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.nombrep.setFont(font)
        self.nombrep.setObjectName(_fromUtf8("nombrep"))
        self.fecha = QtGui.QLabel(SintomaConducta)
        self.fecha.setGeometry(QtCore.QRect(496, 20, 101, 21))
        self.fecha.setText(_fromUtf8(""))
        self.fecha.setObjectName(_fromUtf8("fecha"))
        self.layoutWidget1 = QtGui.QWidget(SintomaConducta)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 50, 651, 81))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.dsvr2 = QtGui.QLineEdit(self.layoutWidget1)
        self.dsvr2.setObjectName(_fromUtf8("dsvr2"))
        self.gridLayout.addWidget(self.dsvr2, 1, 2, 1, 1)
        self.label = QtGui.QLabel(self.layoutWidget1)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.svr1 = QtGui.QComboBox(self.layoutWidget1)
        self.svr1.setObjectName(_fromUtf8("svr1"))
        self.svr1.addItem(_fromUtf8(""))
        self.svr1.addItem(_fromUtf8(""))
        self.svr1.addItem(_fromUtf8(""))
        self.svr1.addItem(_fromUtf8(""))
        self.svr1.addItem(_fromUtf8(""))
        self.svr1.addItem(_fromUtf8(""))
        self.svr1.addItem(_fromUtf8(""))
        self.svr1.addItem(_fromUtf8(""))
        self.svr1.addItem(_fromUtf8(""))
        self.svr1.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.svr1, 0, 1, 1, 1)
        self.svr3 = QtGui.QComboBox(self.layoutWidget1)
        self.svr3.setObjectName(_fromUtf8("svr3"))
        self.svr3.addItem(_fromUtf8(""))
        self.svr3.addItem(_fromUtf8(""))
        self.svr3.addItem(_fromUtf8(""))
        self.svr3.addItem(_fromUtf8(""))
        self.svr3.addItem(_fromUtf8(""))
        self.svr3.addItem(_fromUtf8(""))
        self.svr3.addItem(_fromUtf8(""))
        self.svr3.addItem(_fromUtf8(""))
        self.svr3.addItem(_fromUtf8(""))
        self.svr3.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.svr3, 0, 3, 1, 1)
        self.svr4 = QtGui.QComboBox(self.layoutWidget1)
        self.svr4.setObjectName(_fromUtf8("svr4"))
        self.svr4.addItem(_fromUtf8(""))
        self.svr4.addItem(_fromUtf8(""))
        self.svr4.addItem(_fromUtf8(""))
        self.svr4.addItem(_fromUtf8(""))
        self.svr4.addItem(_fromUtf8(""))
        self.svr4.addItem(_fromUtf8(""))
        self.svr4.addItem(_fromUtf8(""))
        self.svr4.addItem(_fromUtf8(""))
        self.svr4.addItem(_fromUtf8(""))
        self.svr4.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.svr4, 0, 4, 1, 1)
        self.dsvr3 = QtGui.QLineEdit(self.layoutWidget1)
        self.dsvr3.setObjectName(_fromUtf8("dsvr3"))
        self.gridLayout.addWidget(self.dsvr3, 1, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget1)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.dsvr1 = QtGui.QLineEdit(self.layoutWidget1)
        self.dsvr1.setObjectName(_fromUtf8("dsvr1"))
        self.gridLayout.addWidget(self.dsvr1, 1, 1, 1, 1)
        self.dsvr4 = QtGui.QLineEdit(self.layoutWidget1)
        self.dsvr4.setObjectName(_fromUtf8("dsvr4"))
        self.gridLayout.addWidget(self.dsvr4, 1, 4, 1, 1)
        self.svr2 = QtGui.QComboBox(self.layoutWidget1)
        self.svr2.setObjectName(_fromUtf8("svr2"))
        self.svr2.addItem(_fromUtf8(""))
        self.svr2.addItem(_fromUtf8(""))
        self.svr2.addItem(_fromUtf8(""))
        self.svr2.addItem(_fromUtf8(""))
        self.svr2.addItem(_fromUtf8(""))
        self.svr2.addItem(_fromUtf8(""))
        self.svr2.addItem(_fromUtf8(""))
        self.svr2.addItem(_fromUtf8(""))
        self.svr2.addItem(_fromUtf8(""))
        self.svr2.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.svr2, 0, 2, 1, 1)
        self.line = QtGui.QFrame(self.layoutWidget1)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 2, 0, 1, 5)
        self.layoutWidget2 = QtGui.QWidget(SintomaConducta)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 210, 651, 80))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_5 = QtGui.QLabel(self.layoutWidget2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.textAMG = QtGui.QPlainTextEdit(self.layoutWidget2)
        self.textAMG.setObjectName(_fromUtf8("textAMG"))
        self.horizontalLayout.addWidget(self.textAMG)
        self.apellidop = QtGui.QLabel(SintomaConducta)
        self.apellidop.setGeometry(QtCore.QRect(340, 10, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.apellidop.setFont(font)
        self.apellidop.setObjectName(_fromUtf8("apellidop"))
        self.hqd = QtGui.QSpinBox(SintomaConducta)
        self.hqd.setGeometry(QtCore.QRect(140, 480, 71, 27))
        self.hqd.setMaximum(24)
        self.hqd.setObjectName(_fromUtf8("hqd"))

        self.retranslateUi(SintomaConducta)
        QtCore.QMetaObject.connectSlotsByName(SintomaConducta)

    def retranslateUi(self, SintomaConducta):
        SintomaConducta.setWindowTitle(_translate("SintomaConducta", "Sintomatología y Conductas", None))
        self.label_3.setText(_translate("SintomaConducta", "Otros síntomas:", None))
        self.os1.setItemText(0, _translate("SintomaConducta", "Ninguno", None))
        self.os1.setItemText(1, _translate("SintomaConducta", "Problemas de acusión", None))
        self.os1.setItemText(2, _translate("SintomaConducta", "Alergías", None))
        self.os1.setItemText(3, _translate("SintomaConducta", "Resfríos frecuentes", None))
        self.os1.setItemText(4, _translate("SintomaConducta", "Estrés", None))
        self.os1.setItemText(5, _translate("SintomaConducta", "Acidez gástrica", None))
        self.os1.setItemText(6, _translate("SintomaConducta", "Dificultad al tragar", None))
        self.os1.setItemText(7, _translate("SintomaConducta", "Dolor de cuello u hombros", None))
        self.os1.setItemText(8, _translate("SintomaConducta", "Pérdidas anteriores de la voz", None))
        self.os2.setItemText(0, _translate("SintomaConducta", "Ninguno", None))
        self.os2.setItemText(1, _translate("SintomaConducta", "Problemas de acusión", None))
        self.os2.setItemText(2, _translate("SintomaConducta", "Alergías", None))
        self.os2.setItemText(3, _translate("SintomaConducta", "Resfríos frecuentes", None))
        self.os2.setItemText(4, _translate("SintomaConducta", "Estrés", None))
        self.os2.setItemText(5, _translate("SintomaConducta", "Acidez gástrica", None))
        self.os2.setItemText(6, _translate("SintomaConducta", "Dificultad al tragar", None))
        self.os2.setItemText(7, _translate("SintomaConducta", "Dolor de cuello u hombros", None))
        self.os2.setItemText(8, _translate("SintomaConducta", "Pérdidas anteriores de la voz", None))
        self.os3.setItemText(0, _translate("SintomaConducta", "Ninguno", None))
        self.os3.setItemText(1, _translate("SintomaConducta", "Problemas de acusión", None))
        self.os3.setItemText(2, _translate("SintomaConducta", "Alergías", None))
        self.os3.setItemText(3, _translate("SintomaConducta", "Resfríos frecuentes", None))
        self.os3.setItemText(4, _translate("SintomaConducta", "Estrés", None))
        self.os3.setItemText(5, _translate("SintomaConducta", "Acidez gástrica", None))
        self.os3.setItemText(6, _translate("SintomaConducta", "Dificultad al tragar", None))
        self.os3.setItemText(7, _translate("SintomaConducta", "Dolor de cuello u hombros", None))
        self.os3.setItemText(8, _translate("SintomaConducta", "Pérdidas anteriores de la voz", None))
        self.os4.setItemText(0, _translate("SintomaConducta", "Ninguno", None))
        self.os4.setItemText(1, _translate("SintomaConducta", "Problemas de acusión", None))
        self.os4.setItemText(2, _translate("SintomaConducta", "Alergías", None))
        self.os4.setItemText(3, _translate("SintomaConducta", "Resfríos frecuentes", None))
        self.os4.setItemText(4, _translate("SintomaConducta", "Estrés", None))
        self.os4.setItemText(5, _translate("SintomaConducta", "Acidez gástrica", None))
        self.os4.setItemText(6, _translate("SintomaConducta", "Dificultad al tragar", None))
        self.os4.setItemText(7, _translate("SintomaConducta", "Dolor de cuello u hombros", None))
        self.os4.setItemText(8, _translate("SintomaConducta", "Pérdidas anteriores de la voz", None))
        self.label_4.setText(_translate("SintomaConducta", "Descripción:", None))
        self.label_6.setText(_translate("SintomaConducta", "Medicamentos\n"
"que consume:", None))
        self.label_7.setText(_translate("SintomaConducta", "Conductas de\n"
"abuso vocal:", None))
        self.cav1.setItemText(0, _translate("SintomaConducta", "Ninguno", None))
        self.cav1.setItemText(1, _translate("SintomaConducta", "Fumador", None))
        self.cav1.setItemText(2, _translate("SintomaConducta", "Bebe Alcohol", None))
        self.cav1.setItemText(3, _translate("SintomaConducta", "Consumo de alimentos condimentados", None))
        self.cav1.setItemText(4, _translate("SintomaConducta", "Consumo de liquidos (espc. cantidad)", None))
        self.cav1.setItemText(5, _translate("SintomaConducta", "Consumo de café (espc. cantidad)", None))
        self.cav1.setItemText(6, _translate("SintomaConducta", "Pastillas de menta (espc. cantidad)", None))
        self.cav1.setItemText(7, _translate("SintomaConducta", "Intensidad vocal elevada", None))
        self.cav1.setItemText(8, _translate("SintomaConducta", "Realiza actividad física", None))
        self.cav1.setItemText(9, _translate("SintomaConducta", "Se expone a cambios de temperatura", None))
        self.cav1.setItemText(10, _translate("SintomaConducta", "Se expone a calefacción", None))
        self.label_8.setText(_translate("SintomaConducta", "Detalle:", None))
        self.cav2.setItemText(0, _translate("SintomaConducta", "Ninguno", None))
        self.cav2.setItemText(1, _translate("SintomaConducta", "Fumador", None))
        self.cav2.setItemText(2, _translate("SintomaConducta", "Bebe Alcohol", None))
        self.cav2.setItemText(3, _translate("SintomaConducta", "Consumo de alimentos condimentados", None))
        self.cav2.setItemText(4, _translate("SintomaConducta", "Consumo de liquidos (espc. cantidad)", None))
        self.cav2.setItemText(5, _translate("SintomaConducta", "Consumo de café (espc. cantidad)", None))
        self.cav2.setItemText(6, _translate("SintomaConducta", "Pastillas de menta (espc. cantidad)", None))
        self.cav2.setItemText(7, _translate("SintomaConducta", "Intensidad vocal elevada", None))
        self.cav2.setItemText(8, _translate("SintomaConducta", "Realiza actividad física", None))
        self.cav2.setItemText(9, _translate("SintomaConducta", "Se expone a cambios de temperatura", None))
        self.cav2.setItemText(10, _translate("SintomaConducta", "Se expone a calefacción", None))
        self.cav3.setItemText(0, _translate("SintomaConducta", "Ninguno", None))
        self.cav3.setItemText(1, _translate("SintomaConducta", "Fumador", None))
        self.cav3.setItemText(2, _translate("SintomaConducta", "Bebe Alcohol", None))
        self.cav3.setItemText(3, _translate("SintomaConducta", "Consumo de alimentos condimentados", None))
        self.cav3.setItemText(4, _translate("SintomaConducta", "Consumo de liquidos (espc. cantidad)", None))
        self.cav3.setItemText(5, _translate("SintomaConducta", "Consumo de café (espc. cantidad)", None))
        self.cav3.setItemText(6, _translate("SintomaConducta", "Pastillas de menta (espc. cantidad)", None))
        self.cav3.setItemText(7, _translate("SintomaConducta", "Intensidad vocal elevada", None))
        self.cav3.setItemText(8, _translate("SintomaConducta", "Realiza actividad física", None))
        self.cav3.setItemText(9, _translate("SintomaConducta", "Se expone a cambios de temperatura", None))
        self.cav3.setItemText(10, _translate("SintomaConducta", "Se expone a calefacción", None))
        self.cav4.setItemText(0, _translate("SintomaConducta", "Ninguno", None))
        self.cav4.setItemText(1, _translate("SintomaConducta", "Fumador", None))
        self.cav4.setItemText(2, _translate("SintomaConducta", "Bebe Alcohol", None))
        self.cav4.setItemText(3, _translate("SintomaConducta", "Consumo de alimentos condimentados", None))
        self.cav4.setItemText(4, _translate("SintomaConducta", "Consumo de liquidos (espc. cantidad)", None))
        self.cav4.setItemText(5, _translate("SintomaConducta", "Consumo de café (espc. cantidad)", None))
        self.cav4.setItemText(6, _translate("SintomaConducta", "Pastillas de menta (espc. cantidad)", None))
        self.cav4.setItemText(7, _translate("SintomaConducta", "Intensidad vocal elevada", None))
        self.cav4.setItemText(8, _translate("SintomaConducta", "Realiza actividad física", None))
        self.cav4.setItemText(9, _translate("SintomaConducta", "Se expone a cambios de temperatura", None))
        self.cav4.setItemText(10, _translate("SintomaConducta", "Se expone a calefacción", None))
        self.label_9.setText(_translate("SintomaConducta", "Horas que duerme:", None))
        self.label_10.setText(_translate("SintomaConducta", "Paciente:", None))
        self.bguardar.setText(_translate("SintomaConducta", "Guardar", None))
        self.nombrep.setText(_translate("SintomaConducta", "nombre", None))
        self.label.setText(_translate("SintomaConducta", "Síntomas vocales\n"
"relevantes:", None))
        self.svr1.setItemText(0, _translate("SintomaConducta", "Ninguno", None))
        self.svr1.setItemText(1, _translate("SintomaConducta", "Ronquera", None))
        self.svr1.setItemText(2, _translate("SintomaConducta", "Dolor fonar", None))
        self.svr1.setItemText(3, _translate("SintomaConducta", "Fatiga", None))
        self.svr1.setItemText(4, _translate("SintomaConducta", "Sensación de cuerpo extraño", None))
        self.svr1.setItemText(5, _translate("SintomaConducta", "Picor al hablar", None))
        self.svr1.setItemText(6, _translate("SintomaConducta", "Carraspera", None))
        self.svr1.setItemText(7, _translate("SintomaConducta", "Tensión al hablar", None))
        self.svr1.setItemText(8, _translate("SintomaConducta", "Resequedad", None))
        self.svr1.setItemText(9, _translate("SintomaConducta", "Esfuerzo al hablar", None))
        self.svr3.setItemText(0, _translate("SintomaConducta", "Ninguno", None))
        self.svr3.setItemText(1, _translate("SintomaConducta", "Ronquera", None))
        self.svr3.setItemText(2, _translate("SintomaConducta", "Dolor fonar", None))
        self.svr3.setItemText(3, _translate("SintomaConducta", "Fatiga", None))
        self.svr3.setItemText(4, _translate("SintomaConducta", "Sensación de cuerpo extraño", None))
        self.svr3.setItemText(5, _translate("SintomaConducta", "Picor al hablar", None))
        self.svr3.setItemText(6, _translate("SintomaConducta", "Carraspera", None))
        self.svr3.setItemText(7, _translate("SintomaConducta", "Tensión al hablar", None))
        self.svr3.setItemText(8, _translate("SintomaConducta", "Resequedad", None))
        self.svr3.setItemText(9, _translate("SintomaConducta", "Esfuerzo al hablar", None))
        self.svr4.setItemText(0, _translate("SintomaConducta", "Ninguno", None))
        self.svr4.setItemText(1, _translate("SintomaConducta", "Ronquera", None))
        self.svr4.setItemText(2, _translate("SintomaConducta", "Dolor fonar", None))
        self.svr4.setItemText(3, _translate("SintomaConducta", "Fatiga", None))
        self.svr4.setItemText(4, _translate("SintomaConducta", "Sensación de cuerpo extraño", None))
        self.svr4.setItemText(5, _translate("SintomaConducta", "Picor al hablar", None))
        self.svr4.setItemText(6, _translate("SintomaConducta", "Carraspera", None))
        self.svr4.setItemText(7, _translate("SintomaConducta", "Tensión al hablar", None))
        self.svr4.setItemText(8, _translate("SintomaConducta", "Resequedad", None))
        self.svr4.setItemText(9, _translate("SintomaConducta", "Esfuerzo al hablar", None))
        self.label_2.setText(_translate("SintomaConducta", "Descripción:", None))
        self.svr2.setItemText(0, _translate("SintomaConducta", "Ninguno", None))
        self.svr2.setItemText(1, _translate("SintomaConducta", "Ronquera", None))
        self.svr2.setItemText(2, _translate("SintomaConducta", "Dolor fonar", None))
        self.svr2.setItemText(3, _translate("SintomaConducta", "Fatiga", None))
        self.svr2.setItemText(4, _translate("SintomaConducta", "Sensación de cuerpo extraño", None))
        self.svr2.setItemText(5, _translate("SintomaConducta", "Picor al hablar", None))
        self.svr2.setItemText(6, _translate("SintomaConducta", "Carraspera", None))
        self.svr2.setItemText(7, _translate("SintomaConducta", "Tensión al hablar", None))
        self.svr2.setItemText(8, _translate("SintomaConducta", "Resequedad", None))
        self.svr2.setItemText(9, _translate("SintomaConducta", "Esfuerzo al hablar", None))
        self.label_5.setText(_translate("SintomaConducta", "Antecedentes\n"
"médicos\n"
"generales:", None))
        self.apellidop.setText(_translate("SintomaConducta", "run", None))

